import { useState } from 'react'
import { updateProjectInfo, useProjectInfo } from '../../core/state/project-store'
import { bearingCapacity, foundationChecks, jetGrout, liquefaction, settlement, sptCorrection, stressAtDepth, SOURCE_NOTES, type BearingMethod, type SoilLayerInput } from '../../core/calculations/engineering'
import { demoBoreholes, demoLaboratory, type BoreholeRecord, type LaboratoryRecord } from '../../core/models/field-data'
import FieldInvestigation from './FieldInvestigation'
import { Card, Field, Frame, Metric, Source, Table, type ScreenId } from '../workspace/WorkspaceShell'

export const layers: SoilLayerInput[] = [
  { top: 0, bottom: 1.5, soil: 'Dolgu', gamma: 18, gammaSat: 19, cohesion: 5, phi: 20, fines: 25 },
  { top: 1.5, bottom: 5, soil: 'CIL', gamma: 18.2, gammaSat: 19, cohesion: 18, phi: 24, fines: 70 },
  { top: 5, bottom: 9, soil: 'siSa', gamma: 18.5, gammaSat: 19.2, cohesion: 5, phi: 30, fines: 20 },
  { top: 9, bottom: 15, soil: 'Sa', gamma: 18.7, gammaSat: 19.5, cohesion: 2, phi: 34, fines: 8 }
]

export function ProjectInfo() {
  const p = useProjectInfo()
  const set = (key: keyof typeof p, value: unknown) => updateProjectInfo({ ...p, [key]: value })
  return <Frame screen="project-info"><div className="form-section"><div className="section-title">PROJE KİMLİĞİ</div><div className="form-grid"><Field label="Proje Adı" type="text" value={p.title} onChange={(v) => set('title', v)} /><Field label="Proje No" type="text" value={p.projectNo} onChange={(v) => set('projectNo', v)} /><Field label="Tarih" type="date" value={p.date} onChange={(v) => set('date', v)} /><Field label="Mühendis" type="text" value={p.engineer} onChange={(v) => set('engineer', v)} /><Field label="İl" type="text" value={p.province} onChange={(v) => set('province', v)} /><Field label="İlçe" type="text" value={p.district} onChange={(v) => set('district', v)} /><Field label="Adres" type="text" value={p.address} onChange={(v) => set('address', v)} /><Field label="Parsel" type="text" value={p.parcelInfo} onChange={(v) => set('parcelInfo', v)} /><Field label="Yapı Türü" type="text" value={p.buildingType} onChange={(v) => set('buildingType', v)} /></div></div><div className="form-section"><div className="section-title">MERKEZİ ZEMİN / TEMEL GİRDİLERİ</div><div className="form-grid"><Field label="γ (kN/m³)" value={p.soilParameters.unitWeight} onChange={(v) => set('soilParameters', { ...p.soilParameters, unitWeight: +v })} /><Field label="c (kPa)" value={p.soilParameters.cohesion} onChange={(v) => set('soilParameters', { ...p.soilParameters, cohesion: +v })} /><Field label="φ (°)" value={p.soilParameters.frictionAngle} onChange={(v) => set('soilParameters', { ...p.soilParameters, frictionAngle: +v })} /><Field label="B (m)" value={p.foundationParameters.footingWidth} onChange={(v) => set('foundationParameters', { ...p.foundationParameters, footingWidth: +v })} /><Field label="Df (m)" value={p.foundationParameters.footingDepth} onChange={(v) => set('foundationParameters', { ...p.foundationParameters, footingDepth: +v })} /><Field label="FS" value={p.foundationParameters.safetyFactor} onChange={(v) => set('foundationParameters', { ...p.foundationParameters, safetyFactor: +v })} /></div></div></Frame>
}

export function Dashboard({ onNavigate }: { onNavigate: (id: ScreenId) => void }) { const p = useProjectInfo(); const items: [string, string, ScreenId][] = [['01', 'Proje bilgileri', 'project-info'], ['02', 'Saha ve sondaj', 'field'], ['03', 'Zemin profili', 'profile'], ['04', 'Deprem parametreleri', 'earthquake'], ['05', 'Taşıma gücü', 'bearing-capacity'], ['06', 'Oturma', 'settlement'], ['07', 'Sıvılaşma', 'liquefaction'], ['08', 'Temel tasarımı', 'foundation'], ['09', 'Jet Grout', 'jet-grout'], ['10', 'Mühendislik raporu', 'report']]; return <Frame screen="dashboard"><div className="dashboard-grid"><Card title="PROJE DURUMU"><div className="form-grid"><Metric label="Proje" value={p.title || 'Yeni Proje'} /><Metric label="Proje No" value={p.projectNo || '—'} /><Metric label="Birim Sistemi" value={p.unitSystem} /><Metric label="Yapı" value={p.buildingType || '—'} /></div></Card><Card title="MÜHENDİSLİK İŞ AKIŞI"><div className="workflow">{items.map(([n, label, id]) => <button key={id} onClick={() => onNavigate(id)}><b>{n}</b><span>{label}</span></button>)}</div></Card></div></Frame> }

export function FieldScreen({ boreholes, labs, onBoreholesChange, onLabsChange }: { boreholes: BoreholeRecord[]; labs: LaboratoryRecord[]; onBoreholesChange: (x: BoreholeRecord[]) => void; onLabsChange: (x: LaboratoryRecord[]) => void }) { return <Frame screen="field"><FieldInvestigation boreholes={boreholes} labs={labs} onBoreholesChange={onBoreholesChange} onLabsChange={onLabsChange} /></Frame> }

export function Profile() { const [gwt, setGwt] = useState(6.2); const rows = layers.map((l) => { const s = stressAtDepth(l.bottom, layers, gwt); return [l.soil, `${l.top}–${l.bottom}`, l.gamma, l.cohesion, l.phi, s.sigmaV.toFixed(1), s.sigmaVPrime.toFixed(1)] }); return <Frame screen="profile"><Source>{SOURCE_NOTES.investigation}</Source><div className="form-grid"><Field label="Yeraltı su seviyesi (m)" value={gwt} onChange={(v) => setGwt(+v)} /></div><Card title="ZEMİN PROFİLİ"><div className="profile-visual"><div className="depth-scale">{[0, 3, 6, 9, 12, 15].map((d) => <span key={d} style={{ top: `${d / 15 * 100}%` }}>{d} m</span>)}</div><div className="soil-column">{layers.map((l) => <div key={l.soil + l.top} className="layer" style={{ height: `${(l.bottom - l.top) / 15 * 100}%` }}>{l.soil}<small>c={l.cohesion} kPa · φ={l.phi}°</small></div>)}</div></div></Card><Card title="KATMAN / GERİLME TABLOSU"><Table headers={['Zemin', 'Derinlik', 'γ', 'c', 'φ', 'σv', 'σ′v']} rows={rows} /></Card></Frame> }

export function Earthquake() { const [ss, setSs] = useState(1), [s1, setS1] = useState(.3), [fs, setFs] = useState(1), [f1, setF1] = useState(1); const sds = ss * fs, sd1 = s1 * f1, TA = .2 * sd1 / sds, TB = sd1 / sds; const points = Array.from({ length: 30 }, (_, i) => .05 + i * .25).map((T) => [T, T <= TA ? sds * (.4 + .6 * T / TA) : T <= TB ? sds : sd1 / T]); return <Frame screen="earthquake"><Source>AFAD Türkiye Deprem Tehlike Haritası ve TBDY 2018 Bölüm 2. Ss/S1 ve Fs/F1 kullanıcı girdileridir.</Source><div className="form-grid"><Field label="Ss" value={ss} onChange={(v) => setSs(+v)} /><Field label="S1" value={s1} onChange={(v) => setS1(+v)} /><Field label="Fs" value={fs} onChange={(v) => setFs(+v)} /><Field label="F1" value={f1} onChange={(v) => setF1(+v)} /></div><div className="metric-strip"><Metric label="SDS" value={sds.toFixed(3)} /><Metric label="SD1" value={sd1.toFixed(3)} /><Metric label="TA" value={TA.toFixed(3)} unit="s" /><Metric label="TB" value={TB.toFixed(3)} unit="s" /></div><Card title="ELASTİK SPEKTRUM"><Table headers={['T (s)', 'Sa (g)']} rows={points.map((x) => [x[0].toFixed(2), x[1].toFixed(3)])} /></Card></Frame> }

export function Bearing() { const p = useProjectInfo(); const [method, setMethod] = useState<BearingMethod>('Terzaghi'); const r = bearingCapacity({ B: p.foundationParameters.footingWidth, L: p.foundationParameters.footingWidth, Df: p.foundationParameters.footingDepth, gamma: p.soilParameters.unitWeight, c: p.soilParameters.cohesion, phi: p.soilParameters.frictionAngle, FS: p.foundationParameters.safetyFactor, method }); return <Frame screen="bearing-capacity"><Source>{SOURCE_NOTES.bearing}</Source><div className="form-grid"><label><span>Yöntem</span><select value={method} onChange={(e) => setMethod(e.target.value as BearingMethod)}>{(['Terzaghi', 'Meyerhof', 'Hansen', 'Vesic'] as BearingMethod[]).map((x) => <option key={x}>{x}</option>)}</select></label></div><div className="metric-strip"><Metric label="Nc" value={r.Nc.toFixed(2)} /><Metric label="Nq" value={r.Nq.toFixed(2)} /><Metric label="Nγ" value={r.Ngamma.toFixed(2)} /><Metric label="qult" value={r.ultimate.toFixed(1)} unit="kPa" tone="primary" /><Metric label="qallow" value={r.allowableGross.toFixed(1)} unit="kPa" tone="primary" /></div><Card title="HESAP İZİ"><div className="formula-large">q = cNc + qNq + 0.5γBNγ</div></Card></Frame> }

export function Settlement() { const [q, setQ] = useState(150), [B, setB] = useState(2), [Es, setEs] = useState(25000), [nu, setNu] = useState(.3), [H, setH] = useState(4), [Cc, setCc] = useState(.25), [e0, setE0] = useState(1), [s0, setS0] = useState(100), [ds, setDs] = useState(60); const r = settlement({ B, q, Es, nu, layers: [{ thickness: H, Cc, e0, sigma0: s0, dSigma: ds }] }); return <Frame screen="settlement"><Source>{SOURCE_NOTES.settlement}</Source><div className="form-grid"><Field label="q (kPa)" value={q} onChange={(v) => setQ(+v)} /><Field label="B (m)" value={B} onChange={(v) => setB(+v)} /><Field label="Es (kPa)" value={Es} onChange={(v) => setEs(+v)} /><Field label="ν" value={nu} onChange={(v) => setNu(+v)} /><Field label="H (m)" value={H} onChange={(v) => setH(+v)} /><Field label="Cc" value={Cc} onChange={(v) => setCc(+v)} /><Field label="e0" value={e0} onChange={(v) => setE0(+v)} /><Field label="σ′0" value={s0} onChange={(v) => setS0(+v)} /><Field label="Δσ′" value={ds} onChange={(v) => setDs(+v)} /></div><div className="metric-strip"><Metric label="Elastik" value={(r.immediate * 1000).toFixed(1)} unit="mm" /><Metric label="Konsolidasyon" value={(r.consolidation * 1000).toFixed(1)} unit="mm" /><Metric label="Toplam" value={(r.total * 1000).toFixed(1)} unit="mm" tone="primary" /></div></Frame> }

export function Liquefaction() { const [mw, setMw] = useState(7.2), [sds, setSds] = useState(.7), [depth, setDepth] = useState(6), [n, setN] = useState(20), [fines, setFines] = useState(15); const s = stressAtDepth(depth, layers, 3), c = sptCorrection({ depth, nField: n, fines }, s.sigmaVPrime), r = liquefaction({ Mw: mw, Sds: sds, depth, N160f: c.N160f, sigmaV: s.sigmaV, sigmaVPrime: s.sigmaVPrime }); return <Frame screen="liquefaction"><Source>{SOURCE_NOTES.liquefaction}</Source><div className="form-grid"><Field label="Mw" value={mw} onChange={(v) => setMw(+v)} /><Field label="SDS" value={sds} onChange={(v) => setSds(+v)} /><Field label="Derinlik (m)" value={depth} onChange={(v) => setDepth(+v)} /><Field label="N saha" value={n} onChange={(v) => setN(+v)} /><Field label="İnce dane (%)" value={fines} onChange={(v) => setFines(+v)} /></div><div className="metric-strip"><Metric label="N60" value={c.N60.toFixed(1)} /><Metric label="N1,60" value={c.N160.toFixed(1)} /><Metric label="N1,60f" value={c.N160f.toFixed(1)} /><Metric label="Rτ/τdeprem" value={r.ratio.toFixed(2)} tone={r.safe ? 'primary' : ''} /></div><Card title="EK 16B HESAP İZİ"><Table headers={['CE', 'CB', 'CS', 'CR', 'CN', 'CRR7.5', 'CM', 'Rτ', 'τdeprem']} rows={[[c.CE.toFixed(2), c.CB.toFixed(2), c.CS.toFixed(2), c.CR.toFixed(2), c.CN.toFixed(2), r.CRRM75.toFixed(4), r.CM.toFixed(3), r.Rtau.toFixed(1), r.tau.toFixed(1)]]} /></Card></Frame> }

export function Foundation() { const [N, setN] = useState(900), [V, setV] = useState(120), [Mx, setMx] = useState(80), [My, setMy] = useState(60), [B, setB] = useState(2.5), [L, setL] = useState(2.5); const r = foundationChecks({ B, L, N, V, Mx, My }); return <Frame screen="foundation"><Source>{SOURCE_NOTES.foundation}</Source><div className="form-grid"><Field label="N (kN)" value={N} onChange={(v) => setN(+v)} /><Field label="V (kN)" value={V} onChange={(v) => setV(+v)} /><Field label="Mx (kNm)" value={Mx} onChange={(v) => setMx(+v)} /><Field label="My (kNm)" value={My} onChange={(v) => setMy(+v)} /><Field label="B (m)" value={B} onChange={(v) => setB(+v)} /><Field label="L (m)" value={L} onChange={(v) => setL(+v)} /></div><div className="metric-strip"><Metric label="eX" value={r.ex.toFixed(3)} unit="m" /><Metric label="eY" value={r.ey.toFixed(3)} unit="m" /><Metric label="qort" value={r.qAvg.toFixed(1)} unit="kPa" /><Metric label="qmax" value={r.qMax.toFixed(1)} unit="kPa" tone="primary" /></div></Frame> }

export function JetGrout() { const [d, setD] = useState(.6), [s, setS] = useState(1), [qs, setQs] = useState(150), [qc, setQc] = useState(5000), [imp, setImp] = useState(1), [fs, setFs] = useState(2), [sc, setSc] = useState(5000); const r = jetGrout({ columnDiameter:d, spacing:s, qultSoil:qs, qultColumn:qc, improvementFactor:imp, FS:fs, columnStrength:sc }); return <Frame screen="jet-grout"><Source>{SOURCE_NOTES.jetGrout}</Source><div className="form-grid"><Field label="Kolon çapı (m)" value={d} onChange={(v)=>setD(+v)}/><Field label="Aks aralığı (m)" value={s} onChange={(v)=>setS(+v)}/><Field label="Zemin qult (kPa)" value={qs} onChange={(v)=>setQs(+v)}/><Field label="Jet Grout qult (kPa)" value={qc} onChange={(v)=>setQc(+v)}/><Field label="İyileştirme katsayısı" value={imp} onChange={(v)=>setImp(+v)}/><Field label="FS" value={fs} onChange={(v)=>setFs(+v)}/><Field label="Kolon dayanımı (kPa)" value={sc} onChange={(v)=>setSc(+v)}/></div><div className="metric-strip"><Metric label="Alan oranı" value={(r.ratio*100).toFixed(1)} unit="%"/><Metric label="Kompozit qult" value={r.composite.toFixed(1)} unit="kPa"/><Metric label="İzin verilebilir" value={r.allowable.toFixed(1)} unit="kPa" tone="primary"/></div></Frame> }

export function Report() { const p=useProjectInfo(); return <Frame screen="report"><Source>Rapor çıktısı, proje veri modeli ve hesap modüllerinden üretilecektir.</Source><Card title="RAPOR ÖZETİ"><div className="metric-strip"><Metric label="Proje" value={p.title||'Yeni Proje'}/><Metric label="Proje No" value={p.projectNo||'—'}/><Metric label="İl / İlçe" value={`${p.province||'—'} / ${p.district||'—'}`}/></div></Card></Frame> }
