import { useMemo } from 'react'
import { Frame } from '../workspace/WorkspaceShell'
import type { BoreholeRecord, LaboratoryRecord } from '../../../core/models/field-data'
import { useProjectInfo } from '../../../core/state/project-store'
import { deriveSptValues } from '../../../core/engineering/field-calculations'
import { bearingCapacity, tbdyBearingCapacity, liquefactionProfile, layerSettlement, schmertmann, stressSpread2to1, subgradeReaction } from '../../../core/calculations/engineering'
import { latestJetGroutResult } from './JetGroutEngineeringScreen'
import { forceToBase, momentToBase, stressToBase, unitWeightToBase } from '../../../core/units/project-units'
import './engineering-report.css'

type Props={boreholes:BoreholeRecord[];labs:LaboratoryRecord[]}
const fmt=(v?:number,d=2)=>v===undefined||!Number.isFinite(v)?'—':v.toFixed(d)
const chunks=<T,>(a:T[],n:number)=>Array.from({length:Math.ceil(a.length/n)},(_,i)=>a.slice(i*n,(i+1)*n))
function Page({children,landscape=false,className='' }:{children:React.ReactNode;landscape?:boolean;className?:string}){return <section className={`report-page ${landscape?'report-landscape':'report-portrait'} ${className}`}>{children}</section>}
function Title({no,kicker,title}:{no:string;kicker:string;title:string}){return <div className="report-section-title"><span>{no}</span><div><small>{kicker}</small><h2>{title}</h2></div></div>}
function Table({children,className='' }:{children:React.ReactNode;className?:string}){return <div className={`report-table-wrap ${className}`}><table className="report-table">{children}</table></div>}
function MetricRow({items}:{items:[string,string][]}){return <div className="report-metrics">{items.map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div>}
function Spectrum({p}:{p:any}){const sds=p.seismic.sds??(p.seismic.ss??0)*(p.seismic.fs??0),sd1=p.seismic.sd1??(p.seismic.s1??0)*(p.seismic.f1??0),ta=p.seismic.ta??(sds>0?.2*sd1/sds:0),tb=p.seismic.tb??(sds>0?sd1/sds:0);const pts=Array.from({length:61},(_,i)=>i/10),v=pts.map(t=>t<=ta?sds*(.4+.6*t/Math.max(ta,.0001)):t<=tb?sds:sd1/Math.max(t,.0001)),m=Math.max(...v,1);return <div className="spectrum-card"><svg viewBox="0 0 720 250"><g className="chart-grid">{[0,1,2,3,4,5].map(i=><line key={i} x1="50" y1={25+i*40} x2="700" y2={25+i*40}/>)}</g><polyline className="spectrum-line" points={pts.map((t,i)=>`${50+t/6*650},${225-v[i]/m*190}`).join(' ')}/><line className="chart-axis" x1="50" y1="225" x2="700" y2="225"/><line className="chart-axis" x1="50" y1="25" x2="50" y2="225"/><text x="355" y="244">T (s)</text><text x="9" y="28">Sa(T)</text></svg><div className="chart-caption"><span>SDS={fmt(sds,3)}</span><span>SD1={fmt(sd1,3)}</span><span>TA={fmt(ta,3)} s</span><span>TB={fmt(tb,3)} s</span></div></div>}
function BarChart({items}:{items:{label:string;value:number}[]}){const max=Math.max(...items.map(x=>Math.abs(x.value)),1);return <div className="bar-chart">{items.map(x=><div className="bar-row" key={x.label}><span>{x.label}</span><div><i style={{width:`${Math.min(100,Math.abs(x.value)/max*100)}%`}}/></div><b>{fmt(x.value,2)}</b></div>)}</div>}
function SoilProfile({rows}:{rows:{from:number;to:number;code:string;description:string}[]}){const h=300,max=Math.max(...rows.map(r=>r.to),1);return <div className="profile-chart"><svg viewBox={`0 0 760 ${h}`} preserveAspectRatio="none"><line x1="90" y1="10" x2="90" y2={h-10} className="chart-axis"/>{rows.map((r,i)=>{const y=10+r.from/max*(h-20),hh=Math.max(3,(r.to-r.from)/max*(h-20));return <g key={i}><rect x="92" y={y} width="330" height={hh} className="profile-layer"/><text x="100" y={y+Math.min(14,Math.max(2,hh-1))}>{r.code||'—'} · {r.description||'—'}</text><text x="430" y={y+12}>{fmt(r.from)}–{fmt(r.to)} m</text></g>})}</svg></div>}
function FoundationSketch({B,L}:{B:number;L:number}){return <div className="cad-sketch"><svg viewBox="0 0 520 220"><rect x="110" y="45" width="300" height="120" className="cad-fill"/><line x1="110" y1="180" x2="410" y2="180" className="cad-line"/><text x="260" y="205">L = {fmt(L)} m</text><line x1="430" y1="45" x2="430" y2="165" className="cad-line"/><text x="470" y="110">B = {fmt(B)} m</text><text x="260" y="108">TEMEL PLANI</text></svg></div>}
function JetGroutSketch({d,s,layout}:{d:number;s:number;layout:string}){return <div className="cad-sketch"><svg viewBox="0 0 520 220"><rect x="80" y="35" width="360" height="150" className="cad-grid-fill"/>{[0,1,2,3,4].map(i=>[0,1,2].map(j=><circle key={`${i}-${j}`} cx={115+i*80+(layout==='triangular'?(j%2)*40:0)} cy={70+j*55} r="14" className="cad-column"/>))}<text x="260" y="210">d = {fmt(d)} m · s = {fmt(s)} m · {layout==='triangular'?'üçgen':'kare'} yerleşim</text></svg></div>}
export default function EngineeringReportScreen({boreholes,labs}:Props){
 const p=useProjectInfo(),soil=p.soilParameters,f=p.foundationParameters
 const lithology=useMemo(()=>boreholes.flatMap(b=>b.lithology.map(l=>({b:b.name,from:l.from,to:l.to,code:l.code,description:l.description}))),[boreholes])
 const spt=useMemo(()=>boreholes.flatMap(b=>b.spt.filter(s=>s.testType==='SPT'&&Number.isFinite(s.n2)&&Number.isFinite(s.n3)).map(s=>({b:b.name,depth:s.depth,n:s.n2!+s.n3!,v:deriveSptValues(b,s)}))),[boreholes])
 const bearing=useMemo(()=>{if(!(f.footingWidth>0&&f.footingLength>0&&f.verticalLoad>0))return undefined;const base={B:f.footingWidth,L:f.footingLength,Df:f.footingDepth,gamma1:unitWeightToBase(soil.unitWeight,p.unitSystem),gamma2:unitWeightToBase(soil.saturatedUnitWeight,p.unitSystem),c:stressToBase(soil.cohesion,p.unitSystem),phi:soil.frictionAngle,verticalLoad:forceToBase(f.verticalLoad,p.unitSystem),horizontalLoad:forceToBase(f.horizontalLoad,p.unitSystem),momentX:momentToBase(f.momentX,p.unitSystem),momentY:momentToBase(f.momentY,p.unitSystem),groundSlope:soil.surfaceSlope,baseSlope:soil.foundationBaseSlope,resistanceFactor:f.resistanceFactorRv||1.4};return {tbdy:tbdyBearingCapacity(base),methods:(['Terzaghi','Meyerhof','Hansen','Vesic'] as const).map(method=>({method,r:bearingCapacity({B:f.footingWidth,L:f.footingLength,Df:f.footingDepth,gamma:unitWeightToBase(soil.unitWeight,p.unitSystem),c:stressToBase(soil.cohesion,p.unitSystem),phi:soil.frictionAngle,FS:f.safetyFactor||3,method})}))}},[f,soil,p])
 const settlement=useMemo(()=>{if(!(f.footingWidth>0&&f.footingLength>0&&f.verticalLoad>0))return undefined;const q=forceToBase(f.verticalLoad,p.unitSystem)/(f.footingWidth*f.footingLength),Es=Math.max(stressToBase(soil.cohesion,p.unitSystem)*10,1),nu=.3;const raw=boreholes.flatMap(b=>b.lithology);const layers=raw.map(l=>({thickness:Math.max(0,l.to-l.from),sigma0:Math.max(1,l.from*unitWeightToBase(soil.unitWeight,p.unitSystem)),deltaSigma:stressSpread2to1({q,B:f.footingWidth,L:f.footingLength,z:Math.max(0,l.from)}).deltaSigma,Es}));const layer=layerSettlement(layers),sch=schmertmann(q,layers.map(x=>({thickness:x.thickness,Es:x.Es,Iz:Math.max(0,1-x.sigma0/Math.max(x.sigma0+x.deltaSigma,1))}))),ks=subgradeReaction({B:f.footingWidth,Es,nu});return {q,layer,sch,ks,stress:layers.map((x,i)=>({z:raw[i]?.from??0,v:x.deltaSigma,h:x.thickness}))}},[boreholes,f,p,soil])
 const liq=useMemo(()=>{const sds=p.seismic.sds??(p.seismic.ss??0)*(p.seismic.fs??0);const layers=boreholes.flatMap(b=>b.lithology.map(l=>({top:l.from,bottom:l.to,gamma:(l.unitWeight??0)>0?l.unitWeight/10:Math.max(soil.unitWeight/10,1.5),gammaSat:(l.saturatedUnitWeight??0)>0?l.saturatedUnitWeight/10:Math.max(soil.saturatedUnitWeight/10,1.7)})));if(!layers.length||!spt.length)return undefined;const rows=boreholes.flatMap(b=>b.spt.filter(s=>s.testType==='SPT'&&Number.isFinite(s.n2)&&Number.isFinite(s.n3)).map(s=>{const l=b.lithology.find(x=>s.depth>=x.from&&s.depth<x.to);const lab=labs.filter(x=>x.boreholeId===b.id).sort((a,z)=>Math.abs(a.depth-s.depth)-Math.abs(z.depth-s.depth))[0];return {depth:s.depth,nField:s.n2!+s.n3!,soilType:s.soilCode??l?.code??'',fines:lab?.finesContent??lab?.sieve200Passing??l?.finesContent??0,liquidLimit:lab?.liquidLimit??l?.liquidLimit,waterContent:lab?.waterContent,plasticityIndex:lab?.plasticityIndex??l?.plasticityIndex,unitWeightTPerM3:lab?.unitWeight?(lab.unitWeight/10):l?.unitWeight?(l.unitWeight/10):undefined,energyRatio:s.correction?.energyRatio,boreholeDiameterMm:b.drillingDiameter,sampler:'standard' as const,testType:'SPT' as const,id:s.id}}));return liquefactionProfile({Mw:p.seismic.magnitude??7.5,Sds:sds,groundwaterDepth:Math.min(...boreholes.map(b=>b.groundwaterDepth??soil.groundwaterDepth??999)),layers,spt:rows})},[boreholes,labs,p,soil,spt])
 const jet=latestJetGroutResult
 const exportCsv=()=>{const rows=[['Bölüm','Parametre','Değer'],['Proje','Ad',p.title],['Taşıma','TBDY qk',bearing?String(bearing.tbdy.value.qk):''],['Taşıma','TBDY qt',bearing?String(bearing.tbdy.value.qt):''],['Oturma','Tabakalı toplam',settlement?String(settlement.layer.total):''],['Oturma','Schmertmann',settlement?String(settlement.sch.settlement):''],['Sıvılaşma','Kritik FS',liq?String(Math.min(...liq.rows.map(r=>r.fsL))):''],['Jet Grout','Alan oranı',jet?String(jet.areaReplacementRatio):'']];const blob=new Blob([rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${p.projectNo||'ZeminLab'}_hesap_raporu.csv`;a.click();URL.revokeObjectURL(a.href)}
 const print=async()=>{document.body.classList.add('print-report-only');try{await window.api.report.print()}finally{document.body.classList.remove('print-report-only')}};const pdf=async()=>{document.body.classList.add('print-report-only');try{await window.api.report.exportPdf()}finally{document.body.classList.remove('print-report-only')}}
 const lp=chunks(liq?.rows??[],11),bp=chunks(lithology,18),sp=chunks(spt,18)
 return <Frame screen="report"><div className="report-toolbar"><div><b>MÜHENDİSLİK HESAP RAPORU</b><span>A4 dikey · yalnız sıvılaşma A4 yatay</span></div><div><button onClick={exportCsv}>Excel/CSV veri</button><button onClick={print}>Yazdır</button><button onClick={pdf}>PDF çıktısı</button></div></div><article className="report-document">
 <Page className="report-cover-page"><header className="report-cover"><div className="report-brand">ZEMİNLAB</div><div><div className="report-kicker">GEOTEKNİK MÜHENDİSLİK HESAP RAPORU</div><h1>{p.title||'Yeni Proje'}</h1><p>{p.location||'Proje konumu belirtilmemiş'}</p></div><div className="report-meta"><span>Proje No</span><b>{p.projectNo||'—'}</b><span>Tarih</span><b>{p.date||'—'}</b></div></header><div className="report-cover-body"><h2>Hesap ve kontrol raporu</h2><div className="cover-grid"><div><b>İşveren</b><span>{p.clientName||'—'}</span></div><div><b>Firma</b><span>{p.firmName||'—'}</span></div><div><b>Mühendis</b><span>{p.engineer||'—'}</span></div><div><b>Yapı</b><span>{p.buildingType||'—'}</span></div><div><b>İl / İlçe</b><span>{p.province||'—'} / {p.district||'—'}</span></div><div><b>Pafta / Ada / Parsel</b><span>{p.pafta||'—'} / {p.ada||'—'} / {p.parsel||'—'}</span></div></div><div className="report-note">Sayfa yönü otomatik seçilir. Normal hesaplar A4 dikey, geniş sıvılaşma tabloları yalnız A4 yataydır. Tablolar kayıt sınırlarında bölünür; satır ortadan kesilmez.</div></div></Page>
 <Page><Title no="01" kicker="PROJE VE ZEMİN" title="Girdiler ve tasarım temeli"/><div className="report-info-grid"><div><b>Vs30</b><span>{fmt(p.geophysical.vs30,0)} m/s</span></div><div><b>Zemin grubu</b><span>{p.geophysical.soilGroup||'—'}</span></div><div><b>Zemin sınıfı</b><span>{soil.classification.code||'—'}</span></div><div><b>YASS</b><span>{fmt(soil.groundwaterDepth)} m</span></div><div><b>γ</b><span>{fmt(soil.unitWeight)} t/m³</span></div><div><b>γsat</b><span>{fmt(soil.saturatedUnitWeight)} t/m³</span></div><div><b>c′</b><span>{fmt(soil.cohesion)} kPa</span></div><div><b>φ′</b><span>{fmt(soil.frictionAngle)}°</span></div></div><MetricRow items={[["Temel",`${fmt(f.footingWidth)} × ${fmt(f.footingLength)} m`],["Df",`${fmt(f.footingDepth)} m`],["Düşey yük",fmt(f.verticalLoad)],["Yatay yük",fmt(f.horizontalLoad)],["Ss",fmt(p.seismic.ss,3)],["S1",fmt(p.seismic.s1,3)],["Fs / F1",`${fmt(p.seismic.fs,3)} / ${fmt(p.seismic.f1,3)}`],["Mw",fmt(p.seismic.magnitude,2)]]}/><FoundationSketch B={f.footingWidth} L={f.footingLength}/></Page>
 <Page><Title no="02" kicker="SAHA ARAŞTIRMALARI" title="Zemin profili"/>{lithology.length?<SoilProfile rows={lithology}/>:<div className="report-note">Litoloji verisi girilmemiş.</div>}</Page>
 {bp.map((rows,i)=><Page key={`bp${i}`}><Title no="02" kicker="SAHA ARAŞTIRMALARI" title={`Litoloji tablosu · ${i+1}/${bp.length}`}/><Table><thead><tr><th>Sondaj</th><th>Başlangıç</th><th>Bitiş</th><th>Kod</th><th>Zemin tanımı</th></tr></thead><tbody>{rows.map((r,j)=><tr key={j}><td>{r.b}</td><td>{fmt(r.from)}</td><td>{fmt(r.to)}</td><td><b>{r.code}</b></td><td>{r.description}</td></tr>)}</tbody></Table></Page>)}
 {sp.map((rows,i)=><Page key={`sp${i}`}><Title no="03" kicker="SAHA / SPT" title={`SPT düzeltme tablosu · ${i+1}/${sp.length}`}/><Table><thead><tr><th>Sondaj</th><th>z (m)</th><th>N</th><th>Ce</th><th>Cb</th><th>Cs</th><th>Cr</th><th>N60</th><th>CN</th><th>(N1)60</th></tr></thead><tbody>{rows.map((r,j)=><tr key={j}><td>{r.b}</td><td>{fmt(r.depth)}</td><td>{r.n}</td><td>{fmt(r.v.ce)}</td><td>{fmt(r.v.cb)}</td><td>{fmt(r.v.cs)}</td><td>{fmt(r.v.cr)}</td><td>{fmt(r.v.n60)}</td><td>{fmt(r.v.cn)}</td><td>{fmt(r.v.n1_60)}</td></tr>)}</tbody></Table><div className="report-note">SPT düzeltme zinciri: N → Ce → Cb → Cs → Cr → N60 → CN → (N1)60.</div></Page>)}
 <Page><Title no="04" kicker="DEPREM" title="Tasarım spektrumu ve deprem girdileri"/><Spectrum p={p}/><MetricRow items={[["SDS",fmt(p.seismic.sds??(p.seismic.ss??0)*(p.seismic.fs??0),3)],["SD1",fmt(p.seismic.sd1??(p.seismic.s1??0)*(p.seismic.f1??0),3)],["TA",fmt(p.seismic.ta,3)+" s"],["TB",fmt(p.seismic.tb,3)+" s"]]}/></Page>
 <Page><Title no="05" kicker="TAŞIMA GÜCÜ" title="Terzaghi · Meyerhof · Hansen · Vesic ve TBDY"/>{bearing?<><Table><thead><tr><th>Yöntem</th><th>Nq</th><th>Nc</th><th>Nγ</th><th>qult</th><th>qallow gross</th><th>qallow net</th></tr></thead><tbody>{bearing.methods.map(x=><tr key={x.method}><td><b>{x.method}</b></td><td>{fmt(x.r.value.Nq,2)}</td><td>{fmt(x.r.value.Nc,2)}</td><td>{fmt(x.r.value.Ngamma,2)}</td><td>{fmt(x.r.value.ultimate,2)}</td><td>{fmt(x.r.value.allowableGross,2)}</td><td>{fmt(x.r.value.allowableNet,2)}</td></tr>)}</tbody></Table><BarChart items={bearing.methods.map(x=>({label:x.method,value:x.r.value.allowableNet}))}/><Table><thead><tr><th>Adım</th><th>Formül</th><th>Sonuç</th></tr></thead><tbody>{bearing.tbdy.steps.map((x,i)=><tr key={i}><td>{x.symbol}</td><td>{x.formula}</td><td>{fmt(x.value,4)} {x.unit||''}</td></tr>)}</tbody></Table><MetricRow items={[["qk",fmt(bearing.tbdy.value.qk)],["qt",fmt(bearing.tbdy.value.qt)],["q0",fmt(bearing.tbdy.value.qo)],["Kullanım",fmt(bearing.tbdy.value.utilization,3)],["Kontrol",bearing.tbdy.value.adequate?'Sağlanıyor':'Sağlanmıyor']]}/></>:<div className="report-note">Taşıma gücü için yeterli temel/yük girdisi yok.</div>}</Page>
 <Page><Title no="06" kicker="OTURMA" title="Elastik · 2:1 · tabakalı · Schmertmann · ks"/>{settlement?<><MetricRow items={[["q",fmt(settlement.q)+" kPa"],["Tabakalı toplam",fmt(settlement.layer.total*1000)+" mm"],["Elastik",fmt(settlement.layer.immediate*1000)+" mm"],["Konsolidasyon",fmt(settlement.layer.consolidation*1000)+" mm"],["Schmertmann",fmt(settlement.sch.settlement*1000)+" mm"],["ks",fmt(settlement.ks.ks)+" kPa/m"]]}/><Table><thead><tr><th>z</th><th>Δσz</th><th>H</th><th>Yaklaşım</th></tr></thead><tbody>{settlement.stress.map((x,i)=><tr key={i}><td>{fmt(x.z)} m</td><td>{fmt(x.v)} kPa</td><td>{fmt(x.h)} m</td><td>2:1 gerilme yayılımı</td></tr>)}</tbody></Table><div className="settlement-formulas"><b>2:1:</b> Δσz=qBL/[(B+z)(L+z)] · <b>Elastik:</b> s=qB(1−ν²)/Es · <b>Schmertmann:</b> s=C1C2qΣ(Iz/Es)Δz</div></>:<div className="report-note">Oturma hesabı için yeterli temel/yük girdisi yok.</div>}</Page>
 <Page><Title no="07" kicker="TEMEL TABAN KONTROLLERİ" title="Eksantriklik, etkin alan ve şema"/><FoundationSketch B={f.footingWidth} L={f.footingLength}/><Table><thead><tr><th>Kontrol</th><th>Değer</th><th>Bağıntı</th></tr></thead><tbody><tr><td>ex</td><td>{fmt(bearing?.tbdy.value.ex,4)} m</td><td>My/N</td></tr><tr><td>ey</td><td>{fmt(bearing?.tbdy.value.ey,4)} m</td><td>Mx/N</td></tr><tr><td>Be</td><td>{fmt(bearing?.tbdy.value.Be,3)} m</td><td>B−2|ex|</td></tr><tr><td>Le</td><td>{fmt(bearing?.tbdy.value.Le,3)} m</td><td>L−2|ey|</td></tr></tbody></Table></Page>
 {lp.map((rows,i)=><Page landscape key={`liq${i}`}><Title no="08" kicker="SIVILAŞMA · TBDY 2018 EK 16B" title={`SPT profil hesabı · ${i+1}/${lp.length}`}/><div className="landscape-meta"><span>Mw={fmt(p.seismic.magnitude,2)}</span><span>SDS={fmt(p.seismic.sds??(p.seismic.ss??0)*(p.seismic.fs??0),3)}</span><span>YASS={fmt(soil.groundwaterDepth)} m</span><span>{rows.length} kayıt</span></div><Table className="liquefaction-table"><thead><tr><th>z</th><th>Zemin</th><th>N</th><th>Ce</th><th>Cb</th><th>Cs</th><th>Cr</th><th>N60</th><th>CN</th><th>(N1)60</th><th>FC%</th><th>(N1)60f</th><th>σ′v</th><th>CSR</th><th>CRR7.5</th><th>MSF</th><th>FS</th><th>Durum</th></tr></thead><tbody>{rows.map((r,j)=><tr key={j}><td>{fmt(r.depth)}</td><td>{r.soilType||'—'}</td><td>{fmt(r.nField,0)}</td><td>{fmt(r.ce)}</td><td>{fmt(r.cb)}</td><td>{fmt(r.cs)}</td><td>{fmt(r.cr)}</td><td>{fmt(r.n60)}</td><td>{fmt(r.cn)}</td><td>{fmt(r.n1_60)}</td><td>{fmt(r.fines,1)}</td><td>{fmt(r.n1_60f)}</td><td>{fmt(r.sigmaVPrime,1)}</td><td>{fmt(r.csr,3)}</td><td>{fmt(r.crr,3)}</td><td>{fmt(r.msf)}</td><td><b>{fmt(r.fsL)}</b></td><td className={r.conclusion==='SIVILAŞMA VAR'?'report-danger':''}>{r.conclusion}</td></tr>)}</tbody></Table><div className="report-table-foot">{liq?.source} · {liq?.method}</div></Page>)}
 {liq&&<Page landscape><Title no="08" kicker="SIVILAŞMA" title="FS–derinlik grafiği ve kritik kayıtlar"/><div className="fs-chart"><svg viewBox="0 0 900 340"><line x1="90" y1="20" x2="90" y2="310" className="chart-axis"/><line x1="90" y1="310" x2="850" y2="310" className="chart-axis"/><line x1="90" y1="214" x2="850" y2="214" className="threshold-line"/><text x="855" y="218">FS=1.10</text>{liq.rows.map((r,i)=>{const x=90+Math.min(10,Math.max(0,r.fsL))/10*760,y=30+r.depth/Math.max(...liq.rows.map(z=>z.depth),1)*270;return <circle key={i} cx={x} cy={y} r="3" className={r.fsL<1.1?'danger-point':'fs-point'}/>})}<text x="450" y="335">FS</text><text x="18" y="35">z</text></svg></div><Table><thead><tr><th>Derinlik</th><th>FS</th><th>CSR</th><th>CRR7.5</th><th>Durum</th></tr></thead><tbody>{liq.rows.filter(r=>r.fsL<1.1).slice(0,30).map((r,i)=><tr key={i}><td>{fmt(r.depth)} m</td><td><b>{fmt(r.fsL,2)}</b></td><td>{fmt(r.csr,3)}</td><td>{fmt(r.crr,3)}</td><td>{r.conclusion}</td></tr>)}</tbody></Table></Page>}
 <Page><Title no="09" kicker="JET GROUT" title="İyileştirme, yük paylaşımı ve çizim"/>{jet?<><MetricRow items={[["d",fmt(Math.sqrt(4*jet.areaColumn/Math.PI))+" m"],["Acell",fmt(jet.cellArea)+" m²"],["ar",fmt(jet.areaReplacementRatio*100)+" %"],["Ecomp",fmt(jet.compositeModulus)+" kPa"],["Kolon yük payı",fmt(jet.columnLoadShare*100)+" %"],["β",fmt(jet.stressConcentrationFactor)],["Kapasite FS",fmt(jet.capacityFS)],["Sanal radye azalma",fmt(jet.virtualRaft?.reductionPercent)+" %"]]}/><JetGroutSketch d={Math.sqrt(4*jet.areaColumn/Math.PI)} s={Math.sqrt(jet.cellArea)} layout={jet.layout}/><Table><thead><tr><th>Parametre</th><th>Değer</th><th>Bağıntı</th></tr></thead><tbody><tr><td>Alan değiştirme</td><td>{fmt(jet.areaReplacementRatio*100)} %</td><td>Ac/Acell</td></tr><tr><td>Kompozit kapasite</td><td>{fmt(jet.compositeCapacity)} kPa</td><td>ar·qcolumn+(1−ar)·qsoil</td></tr><tr><td>Kompozit modül</td><td>{fmt(jet.compositeModulus)} kPa</td><td>ar·Ec+(1−ar)·Es</td></tr><tr><td>Kolon yük payı</td><td>{fmt(jet.columnLoadShare*100)} %</td><td>(n·ar)/(1+(n−1)ar)</td></tr><tr><td>β</td><td>{fmt(jet.stressConcentrationFactor)}</td><td>ηc/ar</td></tr></tbody></Table>{jet.shearSafety&&<MetricRow items={[["τ",fmt(jet.shearSafety.shearStress)+" kPa"],["τdirenç",fmt(jet.shearSafety.shearResistance)+" kPa"],["FS",fmt(jet.shearSafety.FS)]]}/>} {jet.priebeScreening&&<div className="report-note">Priebe: n₀={fmt(jet.priebeScreening.n0,3)}, n₁={fmt(jet.priebeScreening.n1,3)}. {jet.priebeScreening.warning}</div>}</>:<div className="report-note">Jet Grout hesabı çalıştırılmadan rapor varsayılan parametre üretmez. Bu nedenle sonuç alanı boş bırakılmıştır.</div>}</Page>
 <Page><Title no="10" kicker="SONUÇLAR VE KAYNAK" title="Kontrol özeti"/><Table><thead><tr><th>Hesap</th><th>Sonuç</th><th>Yöntem / kaynak</th></tr></thead><tbody><tr><td>Taşıma gücü</td><td>{bearing?fmt(bearing.tbdy.value.utilization,3):'—'}</td><td>TBDY 2018 Bölüm 16.8.3.2 / Denklem 16.8</td></tr><tr><td>Oturma</td><td>{settlement?fmt(settlement.layer.total*1000)+' mm':'—'}</td><td>Elastik + tabakalı + 2:1 + Schmertmann</td></tr><tr><td>Sıvılaşma</td><td>{liq?fmt(Math.min(...liq.rows.map(r=>r.fsL)),2):'—'}</td><td>TBDY 2018 Ek 16B</td></tr><tr><td>Jet Grout</td><td>{jet?fmt(jet.capacityFS,2):'—'}</td><td>TBDY 2018 Ek 16D + ZeminLab birim hücre modeli</td></tr></tbody></Table><div className="report-note">Kaynak: TBDY 2018 Bölüm 16 ve Ek 16A–16D. Priebe bağıntısı taş kolon/vibro-replacement referansıdır, Jet Grout için doğrudan TBDY katsayısı olarak uygulanmaz. Nihai proje tasarımı ilgili standartlar, proje deneyleri ve kalite kontrol sonuçlarıyla doğrulanmalıdır.</div></Page>
 </article></Frame>
}
