import { useMemo, useState } from 'react'
import { foundationChecks, jetGrout, liquefaction, settlement, SOURCE_NOTES, stressAtDepth } from '../../core/calculations/engineering'
import type { BoreholeRecord, LaboratoryRecord } from '../../core/models/field-data'
import { deriveSptValues } from '../../core/engineering/field-calculations'
import { forceToBase, stressToBase, stressFromBase, PROJECT_UNIT_LABELS } from '../../core/units/project-units'
import { useProjectInfo } from '../../core/state/project-store'
import { Card, Field, Frame, Metric, Source, type ScreenId } from '../workspace/WorkspaceShell'
import { CalculationTrace } from '../components/CalculationTrace'

const finite=(v:number)=>Number.isFinite(v)&&v!==0

export function Dashboard({onNavigate}:{onNavigate:(id:ScreenId)=>void}){const p=useProjectInfo();const items:[string,string,ScreenId][]=[['01','Proje bilgileri','project-info'],['02','Sondaj / SPT / Laboratuvar','field'],['03','Sondaj logları','borehole-log'],['04','Zemin profili','profile'],['05','Taşıma gücü','bearing-capacity'],['06','Oturma','settlement'],['07','Sıvılaşma','liquefaction'],['08','Temel tasarımı','foundation'],['09','Jet Grout','jet-grout'],['10','Mühendislik raporu','report']];return <Frame screen="dashboard"><div className="dashboard-grid"><Card title="PROJE DURUMU"><div className="form-grid"><Metric label="Proje" value={p.title||'Yeni Proje'}/><Metric label="Proje No" value={p.projectNo||'—'}/><Metric label="Birim Sistemi" value={p.unitSystem}/><Metric label="Jeofizik sınıf" value={p.geophysical.soilGroup||'—'}/></div></Card><Card title="MÜHENDİSLİK İŞ AKIŞI"><div className="workflow">{items.map(([n,label,id])=><button key={id} onClick={()=>onNavigate(id)}><b>{n}</b><span>{label}</span></button>)}</div></Card></div></Frame>}

export function Settlement(){const p=useProjectInfo();const s=p.soilParameters;const f=p.foundationParameters;const [method,setMethod]=useState<'elastic+consolidation'|'elastic'>('elastic+consolidation');const ready=finite(f.verticalLoad)&&finite(f.footingWidth)&&finite(s.unitWeight)&&finite(s.cohesion);const q=stressToBase(forceToBase(f.verticalLoad,p.unitSystem)/(Math.max(f.footingWidth*f.footingWidth,1e-9)),p.unitSystem);const Es=finite(s.cohesion)?Math.max(stressToBase(s.cohesion,p.unitSystem)*100,1):0;const r=useMemo(()=>ready?settlement({B:f.footingWidth,q,Es,nu:.3,layers:method==='elastic+consolidation'?[{thickness:Math.max(f.footingDepth,1),Cc:0,e0:1,sigma0:1,dSigma:q}]:[]}):undefined,[ready,f,q,Es,method]);const trace=r?[{symbol:'q',title:'Temel etkime basıncı',formula:'q = N / A',value:stressFromBase(q,p.unitSystem),unit:PROJECT_UNIT_LABELS.stress},{symbol:'sᵢ',title:'Elastik oturma',formula:'sᵢ = q·B·(1−ν²) / Eₛ',value:r.immediate*1000,unit:'mm'},{symbol:'s꜀',title:'Konsolidasyon oturması',formula:'s꜀ = Σ H·Cc/(1+e₀)·log₁₀[(σ′₀+Δσ′)/σ′₀]',value:r.consolidation*1000,unit:'mm'},{symbol:'sₜ',title:'Toplam oturma',formula:'sₜ = sᵢ + s꜀',value:r.total*1000,unit:'mm'}]:[];return <Frame screen="settlement"><Source>{SOURCE_NOTES.settlement}</Source><Card title="HESAP YÖNTEMİ"><label>Model<select value={method} onChange={e=>setMethod(e.target.value as typeof method)}><option value="elastic+consolidation">Elastik + konsolidasyon</option><option value="elastic">Yalnız elastik</option></select></label></Card>{!ready?<Card title="GİRDİ DURUMU"><div className="inline-empty">Oturma için temel yükü, temel genişliği ve zemin parametreleri proje verisinden veya seçilecek korelasyondan sağlanmalıdır.</div></Card>:<><div className="metric-strip"><Metric label="Elastik" value={(r!.immediate*1000).toFixed(2)} unit="mm"/><Metric label="Konsolidasyon" value={(r!.consolidation*1000).toFixed(2)} unit="mm"/><Metric label="Toplam" value={(r!.total*1000).toFixed(2)} unit="mm" tone="primary"/></div><CalculationTrace title="Oturma hesap zinciri" rows={trace} source={SOURCE_NOTES.settlement}/></>}</Frame>}

export function Liquefaction({boreholes=[],labs=[]}:{boreholes?:BoreholeRecord[];labs?:LaboratoryRecord[]}){const p=useProjectInfo();const [selected,setSelected]=useState(boreholes[0]?.id??'');const b=boreholes.find(x=>x.id===selected)??boreholes[0];const spt=b?.spt.find(x=>x.testType==='SPT'&&Number.isFinite(x.n2)&&Number.isFinite(x.n3));const depth=spt?.depth??0;const layer=b?.lithology.find(l=>depth>=l.from&&depth<=l.to);const stress=useMemo(()=>b?stressAtDepth(depth,b.lithology,b.groundwaterDepth??-1):undefined,[b,depth]);const derived=b&&spt?deriveSptValues(b,spt):undefined;const sds=p.seismic.ss&&p.seismic.fs?p.seismic.ss*p.seismic.fs:undefined;const result=derived&&stress&&sds?liquefaction({Mw:7,Sds:sds,depth,N160f:derived.n1_60_dilatancy??derived.n1_60,sigmaV:stress.sigmaV,sigmaVPrime:stress.sigmaVPrime}):undefined;return <Frame screen="liquefaction"><Source>{SOURCE_NOTES.liquefaction}</Source>{!b?<Card title="SONDAJ VERİSİ BEKLENİYOR"><div className="inline-empty">Sıvılaşma hesabı için en az bir sondaj ve hesaplanabilir SPT kaydı gerekir.</div></Card>:<><Card title="HESAP KATMANI"><div className="form-grid"><label>Sondaj<select value={b.id} onChange={e=>setSelected(e.target.value)}>{boreholes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><Metric label="SPT" value={spt?`${spt.depth.toFixed(2)} m`:'—'}/><Metric label="Laboratuvar" value={labs.filter(x=>x.boreholeId===b.id).length}/><Metric label="Zemin" value={layer?.code||'—'}/></div></Card>{!result?<Card title="HESAP İÇİN EKSİK VERİ"><div className="inline-empty">SPT düzeltmesi, etkin gerilme ve deprem girdileri tamamlandığında Ek 16B hesap zinciri oluşturulur.</div></Card>:<><div className="metric-strip"><Metric label="N60" value={derived!.n60.toFixed(2)}/><Metric label="(N1)60" value={derived!.n1_60.toFixed(2)}/><Metric label="CRR" value={result.Rtau.toFixed(3)}/><Metric label="Talep" value={result.tau.toFixed(3)}/><Metric label="Oran" value={result.ratio.toFixed(3)} tone={result.safe?'primary':''}/></div><CalculationTrace title="Ek 16B sıvılaşma hesap zinciri" source={SOURCE_NOTES.liquefaction} rows={[{symbol:'Cₑ·Cᵦ·Cₛ·Cᵣ',title:'SPT saha düzeltmeleri',formula:'N₆₀ = N·Cₑ·Cᵦ·Cₛ·Cᵣ',value:derived!.n60},{symbol:'Cᴺ',title:'Örtü basıncı düzeltmesi',formula:'(N₁)₆₀ = Cᴺ·N₆₀',value:derived!.cn},{symbol:'rᵈ',title:'Derinlik azaltma katsayısı',formula:'rᵈ = f(z)',value:result.rd},{symbol:'CRR',title:'Düzeltilmiş sıvılaşma direnci',formula:'CRR = f[(N₁)₆₀, Mw]',value:result.Rtau},{symbol:'τ',title:'Deprem kayma gerilmesi',formula:'τ = 0.65·σv·(SDS/0.4)·rᵈ',value:result.tau},{symbol:'FS',title:'Direnç / talep oranı',formula:'FS = CRR / τ',value:result.ratio}]}/></>}</>}</Frame>}

export function Foundation(){const p=useProjectInfo();const f=p.foundationParameters;const ready=finite(f.footingWidth)&&finite(f.footingLength)&&finite(f.verticalLoad);const r=ready?foundationChecks({B:f.footingWidth,L:f.footingLength,N:forceToBase(f.verticalLoad,p.unitSystem),V:forceToBase(f.horizontalLoad,p.unitSystem),Mx:forceToBase(f.momentX,p.unitSystem),My:forceToBase(f.momentY,p.unitSystem)}):undefined;return <Frame screen="foundation"><Source>{SOURCE_NOTES.foundation}</Source>{!ready?<Card title="TEMEL VERİSİ BEKLENİYOR"><div className="inline-empty">Geometri ve yükler Proje Bilgileri / temel tanımından bağlanmalıdır.</div></Card>:<><div className="metric-strip"><Metric label="eX" value={r!.ex.toFixed(3)} unit="m"/><Metric label="eY" value={r!.ey.toFixed(3)} unit="m"/><Metric label="qort" value={stressFromBase(r!.qAvg,p.unitSystem).toFixed(3)} unit={PROJECT_UNIT_LABELS.stress}/><Metric label="qmax" value={stressFromBase(r!.qMax,p.unitSystem).toFixed(3)} unit={PROJECT_UNIT_LABELS.stress}/><Metric label="qmin" value={stressFromBase(r!.qMin,p.unitSystem).toFixed(3)} unit={PROJECT_UNIT_LABELS.stress}/></div><CalculationTrace title="Temel gerilme ve eksantriklik hesabı" source={SOURCE_NOTES.foundation} rows={[{symbol:'eₓ',title:'Eksantriklik',formula:'eₓ = Mᵧ / N',value:r!.ex,unit:'m'},{symbol:'eᵧ',title:'Eksantriklik',formula:'eᵧ = Mₓ / N',value:r!.ey,unit:'m'},{symbol:'q̄',title:'Ortalama taban gerilmesi',formula:'q̄ = N / (B·L)',value:stressFromBase(r!.qAvg,p.unitSystem),unit:PROJECT_UNIT_LABELS.stress},{symbol:'qmax',title:'Maksimum taban gerilmesi',formula:'qmax = q̄[1 + 6eₓ/L + 6eᵧ/B]',value:stressFromBase(r!.qMax,p.unitSystem),unit:PROJECT_UNIT_LABELS.stress},{symbol:'qmin',title:'Minimum taban gerilmesi',formula:'qmin = q̄[1 − 6eₓ/L − 6eᵧ/B]',value:stressFromBase(r!.qMin,p.unitSystem),unit:PROJECT_UNIT_LABELS.stress},{symbol:'FSv',title:'Kayma güvenliği',formula:'FS = R / V',value:r!.slidingFS}]}/></>}
}

export function JetGrout(){const [d,setD]=useState(''),[spacing,setSpacing]=useState(''),[soil,setSoil]=useState(''),[column,setColumn]=useState(''),[factor,setFactor]=useState(''),[fs,setFs]=useState('');const ready=[d,spacing,soil,column,factor,fs].every(x=>x!==''&&Number(x)>0);const r=ready?jetGrout({columnDiameter:Number(d),spacing:Number(spacing),qultSoil:Number(soil),qultColumn:Number(column),improvementFactor:Number(factor),FS:Number(fs),columnStrength:Number(column)}):undefined;return <Frame screen="jet-grout"><Source>{SOURCE_NOTES.jetGrout}</Source><Card title="JET GROUT TANIMI"><div className="form-grid"><Field label="Kolon çapı (m)" value={d} onChange={setD}/><Field label="Aks aralığı (m)" value={spacing} onChange={setSpacing}/><Field label="Zemin taşıma kapasitesi" value={soil} onChange={setSoil}/><Field label="Kolon dayanımı" value={column} onChange={setColumn}/><Field label="İyileştirme katsayısı" value={factor} onChange={setFactor}/><Field label="FS" value={fs} onChange={setFs}/></div></Card>{r&&<CalculationTrace title="Jet Grout kompozit model" source={SOURCE_NOTES.jetGrout} rows={[{symbol:'A꜀',title:'Kolon alanı',formula:'A꜀ = πd²/4',value:r.Ac,unit:'m²'},{symbol:'ρ',title:'İyileştirme oranı',formula:'ρ = A꜀ / s²',value:r.ratio},{symbol:'qcomp',title:'Kompozit taşıma gücü',formula:'(1−ρ)qsoil + ρ·qcolumn·η',value:r.composite},{symbol:'qallow',title:'İzin verilen değer',formula:'qallow = qcomp / FS',value:r.allowable}]}/>} </Frame>}
