import { useEffect, useMemo, useState } from 'react'
import '../assets/field-workspace.css'
import type { BoreholeRecord, LaboratoryRecord, SptRecord } from '../../../core/models/field-data'

type Props={boreholes:BoreholeRecord[];labs:LaboratoryRecord[];onBoreholesChange:(rows:BoreholeRecord[])=>void;onLabsChange:(rows:LaboratoryRecord[])=>void}
const numericSpt=new Set<keyof SptRecord>(['depth','n1','n2','n3','nSpt'])
const numericLab=new Set<keyof LaboratoryRecord>(['depth','waterContent','unitWeight','liquidLimit','plasticLimit','c','phi'])
const colorClasses:BoreholeRecord['lithology'][number]['colorClass'][]=['fill','clay','silt','sand','gravel','rock']
function sourceLabel(source:string,confirmed?:boolean){if(confirmed)return'Onaylandı';if(source==='image-review')return'Görsel inceleme';if(source==='imported')return'İçe aktarıldı';return'Manuel'}
function blankBorehole(index:number):BoreholeRecord{return{id:crypto.randomUUID(),name:`Sondaj-${String(index).padStart(2,'0')}`,totalDepth:10,groundwaterDepth:undefined,elevation:undefined,location:'',lithology:[{id:crypto.randomUUID(),from:0,to:10,code:'',description:'Tanımlanmamış zemin',colorClass:'fill'}],spt:[]}}

function BoreholeEditor({borehole,onChange,onDelete}:{borehole:BoreholeRecord;onChange:(row:BoreholeRecord)=>void;onDelete:()=>void}){
 const set=(patch:Partial<BoreholeRecord>)=>onChange({...borehole,...patch})
 const layers=borehole.lithology
 const updateLayer=(id:string,patch:Partial<BoreholeRecord['lithology'][number]>)=>set({lithology:layers.map(l=>l.id===id?{...l,...patch}:l)})
 const addLayer=()=>{const from=layers.at(-1)?.to??0;set({lithology:[...layers,{id:crypto.randomUUID(),from,to:from+1,code:'',description:'Yeni tabaka',colorClass:'fill'}]})}
 const removeLayer=(id:string)=>set({lithology:layers.filter(l=>l.id!==id)})
 return <>
  <div className="form-section"><div className="section-title">SONDAJ TANIMI</div><div className="form-grid">
   <label><span>Sondaj adı</span><input type="text" value={borehole.name} onChange={e=>set({name:e.target.value})}/></label>
   <label><span>Toplam derinlik (m)</span><input type="number" step="0.01" value={borehole.totalDepth} onChange={e=>set({totalDepth:Number(e.target.value)})}/></label>
   <label><span>YAS (m)</span><input type="number" step="0.01" value={borehole.groundwaterDepth??''} onChange={e=>set({groundwaterDepth:e.target.value===''?undefined:Number(e.target.value)})}/></label>
   <label><span>Kot (m)</span><input type="number" step="0.01" value={borehole.elevation??''} onChange={e=>set({elevation:e.target.value===''?undefined:Number(e.target.value)})}/></label>
   <label className="wide"><span>Konum / açıklama</span><input type="text" value={borehole.location??''} onChange={e=>set({location:e.target.value})}/></label>
  </div><div className="grid-toolbar"><b>SONDAJI SİL</b><span>Bu işlem sondajın SPT ve ilişkili laboratuvar kayıtlarını da kaldırır.</span><button onClick={onDelete}>SONDAJI SİL</button></div></div>
  <div className="engineering-grid-wrap"><div className="grid-toolbar"><b>LİTOLOJİ / ZEMİN KATLARI</b><span>{layers.length} tabaka</span><button onClick={addLayer}>+ TABAKA</button></div><table className="engineering-grid"><thead><tr><th>Başlangıç</th><th>Bitiş</th><th>Kod</th><th>Açıklama</th><th>Gösterim</th><th/></tr></thead><tbody>{layers.map(l=><tr key={l.id}><td><input type="number" step="0.01" value={l.from} onChange={e=>updateLayer(l.id,{from:Number(e.target.value)})}/></td><td><input type="number" step="0.01" value={l.to} onChange={e=>updateLayer(l.id,{to:Number(e.target.value)})}/></td><td><input value={l.code} onChange={e=>updateLayer(l.id,{code:e.target.value})}/></td><td><input value={l.description} onChange={e=>updateLayer(l.id,{description:e.target.value})}/></td><td><select value={l.colorClass} onChange={e=>updateLayer(l.id,{colorClass:e.target.value as typeof l.colorClass})}>{colorClasses.map(c=><option key={c} value={c}>{c}</option>)}</select></td><td><button className="grid-delete" title="Tabakayı sil" onClick={()=>removeLayer(l.id)}>×</button></td></tr>)}</tbody></table></div>
 </>
}

function SptGrid({borehole,onChange}:{borehole:BoreholeRecord;onChange:(rows:SptRecord[])=>void}){
 const update=(id:string,key:keyof SptRecord,value:string)=>onChange(borehole.spt.map(row=>row.id!==id?row:{...row,[key]:numericSpt.has(key)?(value===''?undefined:Number(value)):value,source:'manual',confirmed:false}))
 const add=()=>onChange([...borehole.spt,{id:crypto.randomUUID(),depth:(borehole.spt.at(-1)?.depth??0)+1.5,testType:'SPT',source:'manual',confirmed:false}])
 return <div className="engineering-grid-wrap"><div className="grid-toolbar"><b>SPT KAYITLARI</b><span>{borehole.spt.length} kayıt</span><button onClick={add}>+ SPT SATIRI</button></div><table className="engineering-grid"><thead><tr><th>Derinlik</th><th>Tip</th><th>N1</th><th>N2</th><th>N3</th><th>N-SPT</th><th>Zemin</th><th>Açıklama</th><th>Durum</th><th/></tr></thead><tbody>{borehole.spt.map(row=><tr key={row.id}><td><input type="number" step="0.01" value={row.depth} onChange={e=>update(row.id,'depth',e.target.value)}/></td><td><select value={row.testType} onChange={e=>update(row.id,'testType',e.target.value)}><option value="SPT">SPT</option><option value="UD">UD</option></select></td>{(['n1','n2','n3','nSpt'] as const).map(key=><td key={key}><input type="number" value={row[key]??''} onChange={e=>update(row.id,key,e.target.value)}/></td>)}<td><input value={row.soilCode??''} onChange={e=>update(row.id,'soilCode',e.target.value)}/></td><td><input value={row.soilDescription??''} onChange={e=>update(row.id,'soilDescription',e.target.value)}/></td><td><span className={row.confirmed?'source-confirmed':'source-review'}>{sourceLabel(row.source,row.confirmed)}</span></td><td><button className="grid-delete" title="Kaydı sil" onClick={()=>onChange(borehole.spt.filter(x=>x.id!==row.id))}>×</button></td></tr>)}</tbody></table></div>
}

function LaboratoryGrid({rows,boreholes,onChange}:{rows:LaboratoryRecord[];boreholes:BoreholeRecord[];onChange:(rows:LaboratoryRecord[])=>void}){
 const update=(id:string,key:keyof LaboratoryRecord,value:string)=>onChange(rows.map(row=>row.id!==id?row:{...row,[key]:numericLab.has(key)?(value===''?undefined:Number(value)):value,source:'manual',confirmed:false}))
 const add=()=>onChange([...rows,{id:crypto.randomUUID(),boreholeId:boreholes[0]?.id??'',sampleId:`NUM-${String(rows.length+1).padStart(2,'0')}`,depth:1,sampleType:'UD',source:'manual',confirmed:false}])
 return <div className="engineering-grid-wrap"><div className="grid-toolbar"><b>LABORATUVAR DENEYLERİ</b><span>{rows.length} numune</span><button onClick={add}>+ NUMUNE</button></div><table className="engineering-grid"><thead><tr><th>Sondaj</th><th>Numune</th><th>Derinlik</th><th>w %</th><th>γ kN/m³</th><th>LL %</th><th>PL %</th><th>PI %</th><th>c kPa</th><th>φ °</th><th>Durum</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><select value={row.boreholeId} onChange={e=>update(row.id,'boreholeId',e.target.value)}>{boreholes.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></td><td><input value={row.sampleId} onChange={e=>update(row.id,'sampleId',e.target.value)}/></td><td><input type="number" step="0.01" value={row.depth} onChange={e=>update(row.id,'depth',e.target.value)}/></td><td><input type="number" value={row.waterContent??''} onChange={e=>update(row.id,'waterContent',e.target.value)}/></td><td><input type="number" value={row.unitWeight??''} onChange={e=>update(row.id,'unitWeight',e.target.value)}/></td><td><input type="number" value={row.liquidLimit??''} onChange={e=>update(row.id,'liquidLimit',e.target.value)}/></td><td><input type="number" value={row.plasticLimit??''} onChange={e=>update(row.id,'plasticLimit',e.target.value)}/></td><td><input readOnly value={row.liquidLimit!=null&&row.plasticLimit!=null?row.liquidLimit-row.plasticLimit:''}/></td><td><input type="number" value={row.c??''} onChange={e=>update(row.id,'c',e.target.value)}/></td><td><input type="number" value={row.phi??''} onChange={e=>update(row.id,'phi',e.target.value)}/></td><td><span className={row.confirmed?'source-confirmed':'source-review'}>{sourceLabel(row.source,row.confirmed)}</span></td><td><button className="grid-delete" title="Numuneyi sil" onClick={()=>onChange(rows.filter(x=>x.id!==row.id))}>×</button></td></tr>)}</tbody></table></div>
}

function SptVisual({borehole}:{borehole:BoreholeRecord}){const max=Math.max(borehole.totalDepth,1);return <div className="borehole-visual"><div className="depth-ruler">{Array.from({length:Math.floor(max)+1},(_,i)=><span key={i} style={{top:`${(i/max)*100}%`}}>{i} m</span>)}</div><div className="lithology-column">{borehole.lithology.map(layer=><div key={layer.id} className={`lithology-layer ${layer.colorClass}`} style={{top:`${(layer.from/max)*100}%`,height:`${((layer.to-layer.from)/max)*100}%`}}><b>{layer.code||'—'}</b><span>{layer.description}</span></div>)}{borehole.spt.map(row=><div key={row.id} className="spt-marker" style={{top:`${(row.depth/max)*100}%`}}><span>{row.nSpt??'—'}</span></div>)}{borehole.groundwaterDepth!=null&&<div className="gwl-line" style={{top:`${(borehole.groundwaterDepth/max)*100}%`}}><span>YAS {borehole.groundwaterDepth.toFixed(2)} m</span></div>}</div></div>}

export function FieldInvestigation({boreholes,labs,onBoreholesChange,onLabsChange}:Props){
 const [selectedId,setSelectedId]=useState(boreholes[0]?.id??'')
 const [tab,setTab]=useState<'overview'|'borehole'|'spt'|'lab'>('overview')
 useEffect(()=>{if(!boreholes.some(b=>b.id===selectedId))setSelectedId(boreholes[0]?.id??'')},[boreholes,selectedId])
 const selected=boreholes.find(b=>b.id===selectedId)??boreholes[0]
 const labRows=useMemo(()=>labs.filter(row=>row.boreholeId===selected?.id),[labs,selected?.id])
 const addBorehole=()=>{const next=blankBorehole(boreholes.length+1);onBoreholesChange([...boreholes,next]);setSelectedId(next.id);setTab('borehole')}
 const updateBorehole=(row:BoreholeRecord)=>onBoreholesChange(boreholes.map(b=>b.id===row.id?row:b))
 const deleteBorehole=()=>{if(!selected)return;onBoreholesChange(boreholes.filter(b=>b.id!==selected.id));onLabsChange(labs.filter(l=>l.boreholeId!==selected.id));setSelectedId(boreholes.find(b=>b.id!==selected.id)?.id??'');setTab('overview')}
 if(!selected)return <section className="field-workspace"><header className="module-header"><div><div className="module-kicker">SAHA VERİLERİ / SONDAJ</div><h2>Saha verisi</h2><p>Henüz sondaj tanımlanmadı.</p></div><div className="module-actions"><button onClick={addBorehole}>+ YENİ SONDAJ</button></div></header><div className="empty-state"><strong>Henüz sondaj tanımlanmadı.</strong><span>Yeni sondaj ile log, SPT ve laboratuvar verilerini birlikte oluşturabilirsiniz.</span></div></section>
 const patchSpt=(rows:SptRecord[])=>updateBorehole({...selected,spt:rows})
 const patchLabs=(rows:LaboratoryRecord[])=>onLabsChange([...labs.filter(row=>row.boreholeId!==selected.id),...rows])
 return <section className="field-workspace">
  <header className="module-header"><div><div className="module-kicker">SAHA VERİLERİ / SONDAJ</div><h2>{selected.name}</h2><p>{selected.totalDepth.toFixed(2)} m · YAS {selected.groundwaterDepth?.toFixed(2)??'—'} m · {selected.lithology.length} tabaka · {selected.spt.length} SPT</p></div><div className="module-actions"><button onClick={addBorehole}>+ YENİ SONDAJ</button><button onClick={()=>setTab('borehole')}>SONDAJ DÜZENLE</button></div></header>
  <div className="borehole-selector">{boreholes.map(b=><button className={b.id===selected.id?'active':''} key={b.id} onClick={()=>{setSelectedId(b.id);setTab('overview')}}>{b.name}<small>{b.totalDepth.toFixed(2)} m</small></button>)}</div>
  <nav className="module-tabs">{([['overview','Genel'],['borehole','Sondaj Logu'],['spt','SPT'],['lab','Numuneler / Laboratuvar']] as const).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
  {tab==='overview'&&<div className="field-dashboard"><SptVisual borehole={selected}/><aside className="field-side"><div><b>SONDAJ BİLGİSİ</b><p>Derinlik <strong>{selected.totalDepth.toFixed(2)} m</strong></p><p>YAS <strong>{selected.groundwaterDepth?.toFixed(2)??'—'} m</strong></p><p>Kot <strong>{selected.elevation?.toFixed(2)??'—'} m</strong></p><p>SPT <strong>{selected.spt.length}</strong></p></div><div><b>LİTOLOJİ</b>{selected.lithology.map(layer=><p key={layer.id}><span className={`legend ${layer.colorClass}`}/>{layer.from.toFixed(2)}–{layer.to.toFixed(2)} m · {layer.description}</p>)}</div></aside></div>}
  {tab==='borehole'&&<BoreholeEditor borehole={selected} onChange={updateBorehole} onDelete={deleteBorehole}/>} {tab==='spt'&&<SptGrid borehole={selected} onChange={patchSpt}/>} {tab==='lab'&&<LaboratoryGrid rows={labRows} boreholes={boreholes} onChange={patchLabs}/>} 
 </section>
}
