import { useMemo, useState } from 'react'
import { useProjectInfo } from '../../../core/state/project-store'
import { Frame, Card, Metric, Source } from '../workspace/WorkspaceShell'
import type { BoreholeRecord, LaboratoryRecord, SptRecord } from '../../../core/models/field-data'
import type { IdealizedSoilLayer, IdealizedSoilProfile } from '../../../core/models/idealized-soil-profile'
import { createEmptyIdealizedProfile } from '../../../core/models/idealized-soil-profile'
import { deriveSptValues } from '../../../core/engineering/field-calculations'
import { stressToBase, unitWeightToBase } from '../../../core/units/project-units'
import { EngineeringSectionRenderer } from '../components/EngineeringSectionRenderer'

const n=(v:number|undefined)=>v==null||!Number.isFinite(v)?'—':v.toFixed(2)
type Props={boreholes:BoreholeRecord[];labs:LaboratoryRecord[];profile?:IdealizedSoilProfile;onChange:(p:IdealizedSoilProfile)=>void}
function allSpt(boreholes:BoreholeRecord[]){return boreholes.flatMap(b=>b.spt.filter(x=>x.testType==='SPT').map(spt=>({borehole:b,spt})))}
function linkedLab(labs:LaboratoryRecord[],boreholeId:string,sptId:string,depth:number){return labs.find(x=>x.id==='LAB-'+boreholeId+'-'+sptId)??labs.find(x=>x.boreholeId===boreholeId&&Math.abs(x.depth-depth)<0.01)}
const clearLab:Partial<IdealizedSoilLayer>={waterContent:undefined,liquidLimit:undefined,plasticLimit:undefined,plasticityIndex:undefined,finesContent:undefined,gamma:undefined,cohesion:undefined,frictionAngle:undefined,compressionIndexCc:undefined,recompressionIndexCr:undefined,initialVoidRatio:undefined,constrainedModulus:undefined,oedometricModulus:undefined,poissonRatio:undefined}
function labPatch(lab:LaboratoryRecord|undefined,unitSystem:'ton-m'|'kN-m'):Partial<IdealizedSoilLayer>{
 if(!lab)return {}
 return {waterContent:lab.waterContent,liquidLimit:lab.liquidLimit,plasticLimit:lab.plasticLimit,plasticityIndex:lab.plasticityIndex,finesContent:lab.finesContent??lab.sieve200Passing,gamma:lab.unitWeight==null?undefined:unitWeightToBase(lab.unitWeight,unitSystem),cohesion:(lab.directShearC??lab.c??lab.uuC)==null?undefined:stressToBase(lab.directShearC??lab.c??lab.uuC!,unitSystem),frictionAngle:lab.directShearPhi??lab.phi??lab.uuPhi,compressionIndexCc:lab.consolidationCc,recompressionIndexCr:lab.consolidationCs,initialVoidRatio:lab.voidRatio,constrainedModulus:lab.elasticModulus==null?undefined:stressToBase(lab.elasticModulus,unitSystem),oedometricModulus:lab.elasticModulus==null?undefined:stressToBase(lab.elasticModulus,unitSystem),poissonRatio:lab.poissonRatio}
}
function reflow(layers:IdealizedSoilLayer[]){let cursor=0;return layers.map((x,i)=>{const t=Number.isFinite(x.thickness)&&x.thickness!>0?x.thickness!:Math.max(0,x.bottomDepth-x.topDepth);const next={...x,order:i+1,topDepth:cursor,bottomDepth:cursor+t,thickness:t};cursor+=t;return next})}
function sourceOf(spts:Array<{borehole:BoreholeRecord;spt:SptRecord}>,layer:IdealizedSoilLayer){return spts.find(x=>x.borehole.id===layer.sourceBoreholeId&&x.spt.id===layer.sourceSptRecordId)}
function makeLayer(source:{borehole:BoreholeRecord;spt:SptRecord},labs:LaboratoryRecord[],order:number,unitSystem:'ton-m'|'kN-m'):IdealizedSoilLayer{
 const lab=linkedLab(labs,source.borehole.id,source.spt.id,source.spt.depth),patch=labPatch(lab,unitSystem),sptDerived=deriveSptValues(source.borehole,source.spt,labs,unitSystem)
 return {id:crypto.randomUUID(),order,topDepth:0,bottomDepth:0,thickness:0,soilName:source.spt.soilDescription??'Zemin tanımı seçilmedi',soilCode:source.spt.soilCode??'',boreholeIds:[source.borehole.id],sptRecordIds:[source.spt.id],laboratoryRecordIds:lab?[lab.id]:[],sourceBoreholeId:source.borehole.id,sourceSptRecordId:source.spt.id,sourceLaboratoryRecordId:lab?.id,representativeSptN:source.spt.n2!=null&&source.spt.n3!=null?source.spt.n2+source.spt.n3:undefined,representativeN60:sptDerived.n60>0?sptDerived.n60:undefined,representativeN1_60:sptDerived.n1_60>0?sptDerived.n1_60:undefined,parameterSources:lab?{...Object.fromEntries(Object.keys(patch).filter(k=>(patch as Record<string,unknown>)[k]!=null).map(k=>[k,{type:'LABORATUVAR',sampleIds:[lab.id]}]))}: {},userOverride:false,...patch}
}
function label(source:{borehole:BoreholeRecord;spt:SptRecord}){return source.borehole.name+' · '+source.spt.depth.toFixed(2)+' m · '+(source.spt.soilCode??'Zemin seçilmedi')+' · N='+(source.spt.n2!=null&&source.spt.n3!=null?source.spt.n2+source.spt.n3:'—')}
function color(code:string=''){const c=code.toLowerCase();return c.includes('cl')||c.includes('ci')||c.includes('ch')?'clay':c.includes('si')?'silt':c.includes('gr')?'gravel':c.includes('sa')?'sand':'fill'}

export function IdealizedSoilProfileScreen({boreholes,labs,profile,onChange}:Props){
 const p=useMemo(()=>profile??createEmptyIdealizedProfile(),[profile]), project=useProjectInfo(), spts=useMemo(()=>allSpt(boreholes),[boreholes]), [sel,setSel]=useState(0)
 const layers=p.layers,selected=layers[sel],maxDepth=Math.max(1,...layers.map(x=>x.bottomDepth),Number(project.foundationParameters.footingDepth)||0)
 const save=(next:IdealizedSoilLayer[])=>{if(p.status==='SABİTLENDİ')return;onChange({...p,layers:reflow(next),status:'TASLAK',frozenAt:undefined})}
 const add=()=>{if(p.status==='SABİTLENDİ'||!spts.length)return;const used=new Set(layers.map(x=>x.sourceSptRecordId));const src=spts.find(x=>!used.has(x.spt.id))??spts[0];const next=[...layers,makeLayer(src,labs,layers.length+1,project.unitSystem)];setSel(next.length-1);save(next)}
 const remove=()=>{if(p.status==='SABİTLENDİ'||!selected)return;const next=layers.filter((_,i)=>i!==sel);setSel(Math.max(0,Math.min(sel,next.length-1)));save(next)}
 const move=(dir:number)=>{if(p.status==='SABİTLENDİ')return;const j=sel+dir;if(!selected||j<0||j>=layers.length)return;const next=[...layers];[next[sel],next[j]]=[next[j],next[sel]];setSel(j);save(next)}
 const chooseSpt=(i:number,value:string)=>{if(p.status==='SABİTLENDİ')return;const src=spts.find(x=>x.borehole.id+'::'+x.spt.id===value);if(!src)return;const lab=linkedLab(labs,src.borehole.id,src.spt.id,src.spt.depth),patch=labPatch(lab,project.unitSystem),sptDerived=deriveSptValues(src.borehole,src.spt,labs,project.unitSystem);save(layers.map((x,k)=>k!==i?x:{...x,soilName:src.spt.soilDescription??'Zemin tanımı seçilmedi',soilCode:src.spt.soilCode??'',boreholeIds:[src.borehole.id],sptRecordIds:[src.spt.id],laboratoryRecordIds:lab?[lab.id]:[],sourceBoreholeId:src.borehole.id,sourceSptRecordId:src.spt.id,sourceLaboratoryRecordId:lab?.id,representativeSptN:src.spt.n2!=null&&src.spt.n3!=null?src.spt.n2+src.spt.n3:undefined,representativeN60:sptDerived.n60>0?sptDerived.n60:undefined,representativeN1_60:sptDerived.n1_60>0?sptDerived.n1_60:undefined,...clearLab,parameterSources:lab?{...Object.fromEntries(Object.keys(patch).filter(k=>(patch as Record<string,unknown>)[k]!=null).map(k=>[k,{type:'LABORATUVAR',sampleIds:[lab.id]}]))}:{},...patch}))}
 const chooseLab=(i:number,labId:string)=>{if(p.status==='SABİTLENDİ')return;const lab=labId?labs.find(x=>x.id===labId):undefined;save(layers.map((x,k)=>k!==i?x:{...x,sourceLaboratoryRecordId:lab?.id,laboratoryRecordIds:lab?[lab.id]:[],...clearLab,parameterSources:lab?{...x.parameterSources,...Object.fromEntries(Object.keys(labPatch(lab,project.unitSystem)).filter(key=>(labPatch(lab) as Record<string,unknown>)[key]!=null).map(key=>[key,{type:'LABORATUVAR',sampleIds:[lab.id]}]))}:{},...labPatch(lab,project.unitSystem)}))}
 const thickness=(i:number,v:string)=>{if(p.status==='SABİTLENDİ')return;save(layers.map((x,k)=>k===i?{...x,thickness:Math.max(0,Number(v)||0)}:x))}
 const freeze=()=>{if(!layers.length||layers.some(x=>!x.sourceSptRecordId||!x.thickness||x.thickness<=0)){window.alert('Her katmana SPT kaydı seçilmeli ve katman kalınlığı 0’dan büyük girilmelidir.');return}onChange({...p,layers:reflow(layers),unitSystem:'kN-m',status:'SABİTLENDİ',frozenAt:new Date().toISOString(),version:p.version+1})}
 if(!boreholes.length)return <Frame screen="profile"><div className="empty-state"><strong>Önce sondaj ve SPT verisi girilmelidir.</strong></div></Frame>
 if(!spts.length)return <Frame screen="profile"><div className="empty-state"><strong>İdealize profil için en az bir SPT kaydı gerekir.</strong></div></Frame>
 return <Frame screen="profile">
  <div className="idealized-toolbar"><div><b>İDEALİZE ZEMİN PROFİLİ</b><span>Katmanı kullanıcı oluşturur. SPT kaynağı seçilir, kalınlık kullanıcı tarafından girilir, mühendislik özellikleri laboratuvardan alınır.</span></div><div className="idealized-actions"><button disabled={p.status==='SABİTLENDİ'} onClick={add}>＋ Katman Ekle</button><button disabled={!selected} onClick={remove}>Sil</button><button disabled={!selected||sel===0} onClick={()=>move(-1)}>↑</button><button disabled={!selected||sel===layers.length-1} onClick={()=>move(1)}>↓</button><button className="primary-button" disabled={!layers.length} onClick={freeze}>Profili Sabitle</button></div></div>
  <Source>Otomatik korelasyon yapılmaz. Laboratuvarda bulunmayan parametreler boş bırakılır.</Source>
  <div className="metric-strip"><Metric label="Durum" value={p.status}/><Metric label="Katman" value={layers.length}/><Metric label="SPT bağlı" value={layers.filter(x=>x.sourceSptRecordId).length}/><Metric label="LAB bağlı" value={layers.filter(x=>x.sourceLaboratoryRecordId).length}/><Metric label="Toplam kalınlık" value={layers.reduce((a,x)=>a+(x.thickness||0),0).toFixed(2)} unit="m"/><Metric label="Eksik kalınlık" value={layers.filter(x=>!x.thickness||x.thickness<=0).length}/></div>
  <div className="profile-render-card"><div className="profile-render-header"><div><b>GELİŞMİŞ MÜHENDİSLİK KESİT MOTORU</b><span>Vektörel teknik kesit · zemin dokusu · SPT · LAB · YASS · temel tabanı</span></div></div><EngineeringSectionRenderer variant="profile" totalDepth={maxDepth} groundwaterDepth={project.soilParameters.groundwaterDepth} foundationDepth={project.foundationParameters.footingDepth} layers={layers.map(x=>({id:x.id,topDepth:x.topDepth,bottomDepth:x.bottomDepth,code:x.soilCode,description:x.soilName,colorClass:color(x.soilCode),sptN:x.representativeSptN,sptN60:x.representativeN60,gamma:x.gamma,cohesion:x.cohesion,frictionAngle:x.frictionAngle,labId:x.sourceLaboratoryRecordId}))}/></div>
  <Card title="KATMANLAR · SPT KAYNAĞI + LABORATUVAR ÖZELLİKLERİ">
   <div className="profile-layer-editor-head"><span>#</span><span>SPT</span><span>KUYU</span><span>KALINLIK m</span><span>ZEMİN</span><span>LAB</span><span>γ</span><span>c</span><span>φ</span><span>E</span></div>
   <div className="profile-layer-editor">{layers.map((layer,i)=>{const sptKey=layer.sourceBoreholeId&&layer.sourceSptRecordId?layer.sourceBoreholeId+'::'+layer.sourceSptRecordId:'';const labRows=layer.sourceBoreholeId?labs.filter(x=>x.boreholeId===layer.sourceBoreholeId && x.depth>=layer.topDepth && x.depth<=(layer.bottomDepth+1e-9)):[];return <div className={i===sel?'profile-layer-row selected':'profile-layer-row'} key={layer.id} onClick={()=>setSel(i)}>
    <b>{i+1}</b>
    <select value={sptKey} disabled={p.status==='SABİTLENDİ'} onChange={e=>chooseSpt(i,e.target.value)}><option value="">SPT seçiniz</option>{spts.map(src=><option key={src.borehole.id+'::'+src.spt.id} value={src.borehole.id+'::'+src.spt.id}>{label(src)}</option>)}</select>
    <span>{layer.sourceBoreholeId?boreholes.find(x=>x.id===layer.sourceBoreholeId)?.name??'—':'—'}</span>
    <input type="number" min="0" step="0.10" placeholder="Giriniz" value={layer.thickness&&layer.thickness>0?layer.thickness:''} disabled={p.status==='SABİTLENDİ'} onChange={e=>thickness(i,e.target.value)}/>
    <span className="profile-layer-soil"><b>{layer.soilCode||'—'}</b><small>{layer.soilName}</small></span>
    <select value={layer.sourceLaboratoryRecordId??''} disabled={p.status==='SABİTLENDİ'} onChange={e=>chooseLab(i,e.target.value)}><option value="">LAB seçiniz</option>{labRows.map(x=><option key={x.id} value={x.id}>{x.sampleId} · {x.depth.toFixed(2)} m</option>)}</select>
    <span>{n(layer.gamma)}</span><span>{n(layer.cohesion)}</span><span>{n(layer.frictionAngle)}</span><span>{n(layer.oedometricModulus)}</span>
   </div>})}</div>
   {!layers.length&&<div className="inline-empty">“Katman Ekle” ile SPT kaynağı seçerek başlayın.</div>}
  </Card>
  {selected&&<div className="dashboard-grid"><Card title={'SEÇİLİ KATMAN · '+selected.order}><div className="profile-selected-properties"><div><b>Derinlik</b><span>{selected.topDepth.toFixed(2)} – {selected.bottomDepth.toFixed(2)} m</span></div><div><b>Kalınlık</b><span>{(selected.thickness||0).toFixed(2)} m</span></div><div><b>SPT</b><span>{selected.sourceSptRecordId?'Bağlı':'Seçilmedi'}</span></div><div><b>LAB</b><span>{selected.sourceLaboratoryRecordId?'Bağlı':'Seçilmedi'}</span></div><div><b>γ</b><span>{n(selected.gamma)}</span></div><div><b>c</b><span>{n(selected.cohesion)}</span></div><div><b>φ</b><span>{n(selected.frictionAngle)}°</span></div><div><b>Cc</b><span>{n(selected.compressionIndexCc)}</span></div><div><b>e₀</b><span>{n(selected.initialVoidRatio)}</span></div><div><b>E</b><span>{n(selected.oedometricModulus)}</span></div></div></Card><Card title="KAYNAK"><div className="engineering-note">SPT zemin tanımı kaynaktır. (N1)60 değeri TBDY Ek 16B düzeltmeleri uygulanabiliyorsa gösterilir; mühendislik parametreleri seçilen laboratuvar numunesinden taşınır.</div></Card></div>}
 </Frame>
}
export default IdealizedSoilProfileScreen
