import { useMemo, useState } from 'react'
import { calculateIdealizedSettlement, type IdealizedSettlementMethod, type BurlandNTrend } from '../../../core/engineering/idealized-settlement-engine'
import { subgradeReaction } from '../../../core/calculations/engineering'
import type { IdealizedSoilProfile } from '../../../core/models/idealized-soil-profile'
import { forceToBase, forceFromBase, stressFromBase, stressToBase, momentToBase, PROJECT_UNIT_LABELS } from '../../../core/units/project-units'
import type { SubgradeReactionMethod, SubgradeSoilType } from '../../../core/engineering/subgrade-reaction'
import { useProjectInfo } from '../../../core/state/project-store'
import { Card, Frame, Metric, Source, Table } from '../workspace/WorkspaceShell'
import { CalculationTrace } from '../components/CalculationTrace'

const finite=(v:number)=>Number.isFinite(v)&&v>0

function ProfileDiagram({result}:{result:ReturnType<typeof calculateIdealizedSettlement>}){
 const maxDepth=Math.max(result.layers.at(-1)?.bottomDepth??1,1),width=720,height=440,top=52,bottom=410,soilHeight=bottom-top,y=(depth:number)=>top+(depth/maxDepth)*soilHeight
 return <div className="overflow-auto border border-slate-300 bg-white"><svg viewBox={'0 0 '+width+' '+height} width="100%" height="440" role="img" aria-label="Tabaka orta noktaları ve efektif gerilme diyagramı"><rect x="0" y="0" width={width} height={height} fill="#fff"/><rect x="70" y="20" width="150" height="24" fill="#e5e7eb" stroke="#64748b"/><text x="145" y="36" textAnchor="middle" fontSize="12" fontFamily="Segoe UI" fill="#0f172a">TEMEL</text><line x1="70" y1="44" x2="220" y2="44" stroke="#334155" strokeWidth="2"/><text x="235" y="48" fontSize="11" fontFamily="Segoe UI" fill="#334155">Temel kotu Df</text>
 {result.layers.map((layer,index)=>{const yt=y(layer.topDepth),yb=y(layer.bottomDepth),ym=y(layer.midDepth),h=Math.max(yb-yt,18),fill=index%2===0?'#f8fafc':'#eef2f7';return <g key={layer.layerId}><rect x="70" y={yt} width="150" height={h} fill={fill} stroke="#94a3b8"/><text x="145" y={yt+Math.min(h/2+4,20)} textAnchor="middle" fontSize="10" fontFamily="Segoe UI" fill="#0f172a">{layer.soilCode||layer.soilName.slice(0,18)}</text><line x1="250" y1={ym} x2="315" y2={ym} stroke="#64748b" strokeDasharray="4 3"/><circle cx="315" cy={ym} r="4" fill="#0f172a"/><text x="325" y={ym-4} fontSize="10" fontFamily="Segoe UI" fill="#0f172a">zorta = {layer.midDepth.toFixed(2)} m</text><text x="325" y={ym+11} fontSize="10" fontFamily="Segoe UI" fill="#475569">σ′v0 = {layer.sigmaV0Effective.toFixed(1)} kPa</text><text x="500" y={ym-4} fontSize="10" fontFamily="Segoe UI" fill="#475569">Δσ′ = {layer.deltaSigma.toFixed(1)} kPa</text><text x="500" y={ym+11} fontSize="10" fontFamily="Segoe UI" fill="#475569">σ′vf = {layer.sigmaVFinalEffective.toFixed(1)} kPa</text></g>})}<line x1="55" y1={top} x2="55" y2={bottom} stroke="#64748b"/><text x="45" y="31" textAnchor="end" fontSize="10" fontFamily="Segoe UI" fill="#475569">z (m)</text></svg></div>
}

export function IdealizedSettlementScreen({profile}:{profile?:IdealizedSoilProfile}){
 const p=useProjectInfo(),f=p.foundationParameters,[method,setMethod]=useState<IdealizedSettlementMethod>('burland-burbidge'),[burlandNTrend,setBurlandNTrend]=useState<BurlandNTrend>('unknown'),[burlandSoftBottom,setBurlandSoftBottom]=useState(''),[burlandState,setBurlandState]=useState<'NC'|'OC'|'UNKNOWN'>('UNKNOWN'),[burlandPc,setBurlandPc]=useState(''),[timeYears,setTimeYears]=useState(''),[ksMethod,setKsMethod]=useState<SubgradeReactionMethod>('erol-plate'),[kv1Input,setKv1Input]=useState(''),[ksSoilType,setKsSoilType]=useState<SubgradeSoilType>('cohesive')
 const qGross=finite(f.structuralWeight)&&finite(f.footingWidth)&&finite(f.footingLength)?forceToBase(f.structuralWeight,p.unitSystem)/Math.max(f.footingWidth*f.footingLength,1e-9):0
 const groundwaterDepth=p.soilParameters.groundwaterDepth
 const result=useMemo(()=>{if(!profile||profile.status!=='SABİTLENDİ')return undefined;return calculateIdealizedSettlement({profile,method,B:f.footingWidth,L:f.footingLength,Df:f.footingDepth,qGross,groundwaterDepth,verticalLoad:forceToBase(f.structuralWeight,p.unitSystem),momentX:momentToBase(f.momentX,p.unitSystem),momentY:momentToBase(f.momentY,p.unitSystem),foundationType:f.foundationType,burlandNTrend,burlandSoftLayerBottomDepth:burlandSoftBottom===''?undefined:Number(burlandSoftBottom),burlandState:burlandState==='UNKNOWN'?undefined:burlandState,burlandPreconsolidationPressure:burlandPc===''?undefined:stressToBase(Number(burlandPc),p.unitSystem),timeYears:timeYears===''?undefined:Number(timeYears)})},[profile,method,f.footingWidth,f.footingLength,f.footingDepth,qGross,groundwaterDepth,f.foundationType,burlandNTrend,burlandSoftBottom,burlandState,burlandPc,timeYears,p.unitSystem])
 const surfaceLayer=profile?.layers.find(x=>x.bottomDepth>f.footingDepth)
 const ks=useMemo(()=>{if(f.footingWidth<=0||f.footingLength<=0)return undefined;const common={B:f.footingWidth,L:f.footingLength,method:ksMethod,unitSystem:'kN-m' as const};if(ksMethod==='q/s'){if(!result?.ready||result.totalSettlement<=0||qGross<=0)return undefined;return subgradeReaction({...common,q:qGross,settlement:result.totalSettlement/1000})}if(ksMethod==='elastic'){const Es=surfaceLayer?.elasticModulus,nu=surfaceLayer?.poissonRatio;if(!Es||Es<=0||nu==null||nu<0||nu>=0.5)return undefined;return subgradeReaction({...common,Es,nu})}const kv=Number(kv1Input);if(!Number.isFinite(kv)||kv<=0)return undefined;return subgradeReaction({...common,Kv1:forceToBase(kv,p.unitSystem),soilType:ksSoilType})},[surfaceLayer,f.footingWidth,f.footingLength,ksMethod,kv1Input,ksSoilType,p.unitSystem,result,qGross])
 const methodLabel:Record<IdealizedSettlementMethod,string>={'burland-burbidge':'Burland & Burbidge','elasticity':'Elastik tabaka gerinimi (2:1)','2to1-layer':'2:1 + M tabaka','janbu':'Janbu tangent modulus','schmertmann':'Schmertmann'}
 return <Frame screen="settlement"><Source>Oturma yalnız SABİTLENDİ İdealize Zemin Profili üzerinden yürütülür. Profilde c′/φ′, Cu, Es ve M ayrı tutulur; eksik parametreler sıfır kabul edilmez.</Source>
 <Card title="OTURMA YÖNTEMİ"><div className="form-grid"><label>Hesap yöntemi<select value={method} onChange={e=>setMethod(e.target.value as IdealizedSettlementMethod)}><option value="burland-burbidge">Yöntem 1 · Burland &amp; Burbidge</option><option value="elasticity">Yöntem 2 · Es ile elastik tabaka</option><option value="2to1-layer">Yöntem 3 · 2:1 + M</option><option value="janbu">Yöntem 4 · Janbu tangent modulus</option><option value="schmertmann">Yöntem 5 · Schmertmann</option></select></label>
 {method==='burland-burbidge'&&<><label>N60 derinlik eğilimi<select value={burlandNTrend} onChange={e=>setBurlandNTrend(e.target.value as BurlandNTrend)}><option value="unknown">Seçiniz</option><option value="constant-increasing">Sabit / artan</option><option value="decreasing">Azalan</option></select></label>{burlandNTrend==='decreasing'&&<label>Yumuşak tabaka alt kotu (m)<input type="number" min={f.footingDepth} step=".1" value={burlandSoftBottom} onChange={e=>setBurlandSoftBottom(e.target.value)} /></label>}<label>Burland konsolidasyon durumu<select value={burlandState} onChange={e=>setBurlandState(e.target.value as 'NC'|'OC'|'UNKNOWN')}><option value="UNKNOWN">Seçiniz</option><option value="NC">NC</option><option value="OC">OC</option></select></label>{burlandState==='OC'&&<label>{'σ′c ('+PROJECT_UNIT_LABELS[p.unitSystem==='ton-m'?'ton':'kN'].stress+')'}<input type="number" min="0" step="any" value={burlandPc} onChange={e=>setBurlandPc(e.target.value)}/></label>}</>}
 {method==='schmertmann'&&<label>Yükleme süresi t (yıl)<input type="number" min=".1" step=".1" value={timeYears} onChange={e=>setTimeYears(e.target.value)} placeholder="≥ 0.1"/></label>}
 <Metric label="Profil durumu" value={profile?.status??'YOK'}/><Metric label="Katman" value={profile?.layers.length??0}/><Metric label="B′" value={result?.effectiveB?.toFixed(2)??'—'} unit="m"/><Metric label="L′" value={result?.effectiveL?.toFixed(2)??'—'} unit="m"/><Metric label="Df" value={f.footingDepth||'—'} unit="m"/><Metric label="q" value={qGross?stressFromBase(qGross,p.unitSystem):'—'} unit={PROJECT_UNIT_LABELS[p.unitSystem==='ton-m'?'ton':'kN'].stress}/></div></Card>
 {!profile?<Card title="İDEALİZE PROFİL BEKLENİYOR"><div className="inline-empty">Önce İdealize Zemin Profili oluşturulmalıdır.</div></Card>:profile.status!=='SABİTLENDİ'?<Card title="PROFİL SABİTLENMEDİ"><div className="inline-empty">Oturma hesabı için profil SABİTLENDİ olmalıdır.</div></Card>:!result?<Card title="HESAP İÇİN VERİ BEKLENİYOR"><div className="inline-empty">Temel geometrisi, yük ve profil verileri kontrol edilmelidir.</div></Card>:<>{result.warnings.length>0&&<Card title="HESAP NOTLARI"><div className="inline-empty">{result.warnings.join(' ')}</div></Card>}<div className="metric-strip"><Metric label="Ani / birincil" value={result.totalImmediate.toFixed(2)} unit="mm"/><Metric label="Konsolidasyon" value={result.totalConsolidation.toFixed(2)} unit="mm"/><Metric label="Toplam" value={result.totalSettlement.toFixed(2)} unit="mm" tone="primary"/><Metric label="σ′v0 @ Df" value={result.foundationEffectiveStress.toFixed(2)} unit="kPa"/><Metric label="qnet" value={result.netFoundationPressure.toFixed(2)} unit="kPa"/><Metric label="zI" value={result.influenceDepth.toFixed(2)} unit="m"/>{ks&&<Metric label="ks" value={ks.ks.toFixed(2)} unit="kN/m³" />}</div>
 <Card title="ZEMİN YATAK KATSAYISI · ks"><div className="form-grid"><label>Yatak katsayısı yöntemi<select value={ksMethod} onChange={e=>setKsMethod(e.target.value as SubgradeReactionMethod)}><option value="q/s">q/s</option><option value="elastic">Es tabanlı elastik yardımcı yöntem</option><option value="erol-plate">Erol &amp; Çekinmez · plaka yükleme</option></select></label>{ksMethod==='erol-plate'&&<><label>‌Kv1 · 30×30 cm plaka deneyi<input type="number" min="0" step="any" value={kv1Input} onChange={e=>setKv1Input(e.target.value)} placeholder={p.unitSystem==='kN-m'?'kN/m³':'tonf/m³'}/></label><label>Zemin tipi<select value={ksSoilType} onChange={e=>setKsSoilType(e.target.value as SubgradeSoilType)}><option value="cohesive">Kohezyonlu</option><option value="cohesionless">Kohezyonsuz</option></select></label></>}<Metric label="Sonuç" value={ks?forceFromBase(ks.ks,p.unitSystem).toFixed(3):'—'} unit={p.unitSystem==='kN-m'?'kN/m³':'tonf/m³'}/></div><div className="inline-empty">{ksMethod==='erol-plate'?'Kv1 doğrudan plaka deneyinden alınır; temel boyutuna ölçeklenir.':ksMethod==='q/s'?'ks=q/s, burada q ve s aynı hesap zincirinden gelir.':'Es tabanlı yardımcı yaklaşımdır; M ile karıştırılmaz.'}</div></Card>
 <Card title="TABAKA ORTA NOKTALARI · EFEKTİF GERİLMELER"><ProfileDiagram result={result}/></Card>
 <Card title={'TABAKA BAZINDA OTURMA · '+methodLabel[method]}><div className="table-wrap"><table><thead><tr><th>#</th><th>Zemin</th><th>Üst</th><th>Alt</th><th>zorta</th><th>σ′v0</th><th>Δσ′</th><th>σ′vf</th><th>Ani</th><th>Kons.</th><th>Durum</th></tr></thead><tbody>{result.layers.map(l=><tr key={l.layerId}><td>{l.order}</td><td>{l.soilName}</td><td>{l.topDepth.toFixed(2)}</td><td>{l.bottomDepth.toFixed(2)}</td><td>{l.midDepth.toFixed(2)}</td><td>{l.sigmaV0Effective.toFixed(1)}</td><td>{l.deltaSigma.toFixed(1)}</td><td>{l.sigmaVFinalEffective.toFixed(1)}</td><td>{l.immediateSettlement.toFixed(2)}</td><td>{l.consolidationSettlement.toFixed(2)}</td><td>{l.status}</td></tr>)}</tbody></table></div></Card>
 <Card title="HESAP İZİ"><CalculationTrace title="Oturma hesap zinciri" source={result.source} rows={[{symbol:'σ′v0',title:'Temel tabanındaki efektif gerilme',formula:'ΣγH−u',value:result.foundationEffectiveStress,unit:'kPa'},{symbol:'qnet',title:'Net temel ilave basıncı',formula:'qnet=max(0,q−σ′v0)',value:result.netFoundationPressure,unit:'kPa'},{symbol:'zI',title:'Etki derinliği',formula:method==='burland-burbidge'?'1.4·(B/0.3)^0.75·0.3 (trend’e göre ≤2B)':'yönteme göre',value:result.influenceDepth,unit:'m'},{symbol:'sᵢ',title:'Yöntemsel düşey gerinim',formula:method==='burland-burbidge'?'Burland-Burbidge, N̄60 ortalaması':method==='elasticity'?'Σ(Δσ′·H·(1−ν²)/Es)':method==='2to1-layer'?'Σ(Δσ2:1·H/M)':method==='janbu'?'Janbu tangent-modulus integrali': 'Σ(C1·C2·qnet·Iz·H/Es)',value:result.totalImmediate,unit:'mm'},{symbol:'sₜ',title:'Toplam',formula:'s_total=s_method+s_consolidation',value:result.totalSettlement,unit:'mm'}]}/></Card>
 </>}
 </Frame>
}
