import { updateProjectInfo, useProjectInfo } from '../../../core/state/project-store'
import { classifyVs30, type SoilClassificationCode, type FoundationType, type UnitSystem } from '../../../core/models/project'
import { projectUnits } from '../../../core/units/project-units'
import { Card, Field, Frame } from '../workspace/WorkspaceShell'

const descriptions: Record<SoilClassificationCode,string>={CIL:'Düşük plastisiteli kil',CIM:'Orta plastisiteli kil',CIH:'Yüksek plastisiteli kil',SiL:'Düşük plastisiteli silt',SiM:'Orta plastisiteli silt',SiH:'Yüksek plastisiteli silt',ZA:'Sağlam, sert kaya',ZB:'Az ayrışmış, orta sağlam kaya',ZC:'Çok sıkı kum-çakıl / sert kil veya zayıf kaya',ZD:'Orta sıkı-sıkı kum-çakıl / çok katı kil',ZE:'Gevşek kum-çakıl / yumuşak-katı kil',ZF:'Sahaya özel araştırma ve değerlendirme gerektirir'}
const n=(v:string)=>v===''?0:Number(v)
export function ProjectInfoScreenV2(){
 const p=useProjectInfo(),foundation=p.foundationParameters,units=projectUnits(p.unitSystem)
 const set=<K extends keyof typeof p>(key:K,value:(typeof p)[K])=>updateProjectInfo({...p,[key]:value})
 const vs30Group=classifyVs30(p.geophysical.vs30)
 const updateSeismic=(key:keyof typeof p.seismic,value:string)=>set('seismic',{...p.seismic,[key]:value===''?undefined:Number(value)})
 return <Frame screen="project-info"><div className="project-info-layout">
  <Card title="PROJE KİMLİĞİ"><div className="form-grid project-identity-grid"><Field label="Proje Adı" type="text" value={p.title} onChange={v=>set('title',v)}/><Field label="İl" type="text" value={p.province} onChange={v=>set('province',v)}/><Field label="İlçe" type="text" value={p.district} onChange={v=>set('district',v)}/><Field label="Mahalle" type="text" value={p.location} onChange={v=>set('location',v)}/><Field label="Pafta" type="text" value={p.pafta} onChange={v=>set('pafta',v)}/><Field label="Ada" type="text" value={p.ada} onChange={v=>set('ada',v)}/><Field label="Parsel" type="text" value={p.parsel} onChange={v=>set('parsel',v)}/><Field label="Yapı Türü" type="text" value={p.buildingType} onChange={v=>set('buildingType',v)}/><Field label="İmar Durumu" type="text" value={p.zoningStatus} onChange={v=>set('zoningStatus',v)}/><Field label="Kat Sayısı" type="number" value={p.normalFloorCount||''} onChange={v=>set('normalFloorCount',n(v))}/><Field label="Bodrum Sayısı" type="number" value={p.basementCount||''} onChange={v=>set('basementCount',n(v))}/></div></Card>
  <Card title="PROJE BİRİM SİSTEMİ"><div className="form-grid"><label>Hesap birim sistemi<select value={p.unitSystem} onChange={e=>set('unitSystem',e.target.value as UnitSystem)}><option value="ton-m">Ton - m</option><option value="kN-m">kN - m</option></select></label><div className="classification-note"><b>Aktif sistem:</b> {p.unitSystem==='ton-m'?'tonf, tonf/m², tonf/m³, tonf·m':'kN, kN/m², kN/m³, kN·m'}<br/>Bu seçim tüm mühendislik giriş ve sonuçlarının birimlerini belirler.</div></div></Card>
  <Card title="JEOFİZİK · Vs30"><div className="geophysics-panel"><div className="vs30-input"><Field label="Vs30 (m/s)" value={p.geophysical.vs30??''} onChange={v=>set('geophysical',{...p.geophysical,vs30:v===''?undefined:Number(v),soilGroup:classifyVs30(v===''?undefined:Number(v))})}/></div><div className="vs30-result"><span>Otomatik TBDY 2018 zemin grubu</span><strong>{vs30Group??'—'}</strong><small>{vs30Group?descriptions[vs30Group]:'Vs30 girildiğinde otomatik belirlenir.'}</small></div></div><div className="classification-note">ZF, yalnızca özel saha araştırması ve değerlendirmesiyle belirlenebildiğinden Vs30 tek başına ZF ataması yapmaz.</div></Card>
  <Card title="HAZIR DEPREM TEHLİKE PARAMETRELERİ"><div className="form-grid"><Field label="Ss" value={p.seismic.ss??''} onChange={v=>updateSeismic('ss',v)}/><Field label="S1" value={p.seismic.s1??''} onChange={v=>updateSeismic('s1',v)}/><Field label="Fs" value={p.seismic.fs??''} onChange={v=>updateSeismic('fs',v)}/><Field label="F1" value={p.seismic.f1??''} onChange={v=>updateSeismic('f1',v)}/><Field label="Sıvılaşma deprem büyüklüğü Mw" value={p.seismic.magnitude??''} onChange={v=>updateSeismic('magnitude',v)}/></div><div className="classification-note">Ss, S1, Fs ve F1 hazır tehlike girdileridir. Mw yalnızca SPT tabanlı sıvılaşma değerlendirmesi için kullanılan ayrı bir proje girdisidir.</div></Card>
  <Card title="TEMEL TANIMI VE BOYUTLARI"><div className="form-grid foundation-input-grid"><label>Temel tipi<select value={foundation.foundationType} onChange={e=>set('foundationParameters',{...foundation,foundationType:e.target.value as FoundationType})}><option value="tekil">Tekil temel</option><option value="surekli">Sürekli (şerit) temel</option><option value="radye">Radye temel</option></select></label><Field label="Temel Genişliği B (m)" value={foundation.footingWidth||''} onChange={v=>set('foundationParameters',{...foundation,footingWidth:n(v)})}/><Field label="Temel Uzunluğu L (m)" value={foundation.footingLength||''} onChange={v=>set('foundationParameters',{...foundation,footingLength:n(v)})}/><Field label="Temel Derinliği Df (m)" value={foundation.footingDepth||''} onChange={v=>set('foundationParameters',{...foundation,footingDepth:n(v)})}/><Field label={`Yatay yük V (${units.force})`} value={foundation.horizontalLoad||''} onChange={v=>set('foundationParameters',{...foundation,horizontalLoad:n(v)})}/><Field label={`Mx (${units.moment})`} value={foundation.momentX||''} onChange={v=>set('foundationParameters',{...foundation,momentX:n(v)})}/><Field label={`My (${units.moment})`} value={foundation.momentY||''} onChange={v=>set('foundationParameters',{...foundation,momentY:n(v)})}/><Field label={`Yapı Ağırlığı (${units.force})`} value={foundation.structuralWeight||''} onChange={v=>set('foundationParameters',{...foundation,structuralWeight:n(v)})}/><Field label="FS (klasik yöntem)" value={foundation.safetyFactor||''} onChange={v=>set('foundationParameters',{...foundation,safetyFactor:n(v)})}/></div><div className="classification-note structure-weight-note">Temel tipi, taşıma gücü hesaplarındaki şekil katsayılarını belirler. TBDY 2018 Tablo 16.2'ye göre yüzeysel temel taşıma gücü γRv = 1.40'tır.</div></Card>
 </div></Frame>
}
