import { updateProjectInfo, useProjectInfo } from '../../../core/state/project-store'
import { classifyVs30, type SoilClassificationCode, type SoilClassificationSystem } from '../../../core/models/project'
import { Card, Field, Frame, Source } from '../workspace/WorkspaceShell'

const descriptions: Record<SoilClassificationCode, string> = { CIL: 'Düşük plastisiteli kil', CIM: 'Orta plastisiteli kil', CIH: 'Yüksek plastisiteli kil', SiL: 'Düşük plastisiteli silt', SiM: 'Orta plastisiteli silt', SiH: 'Yüksek plastisiteli silt', ZA: 'Sağlam, sert kaya', ZB: 'Az ayrışmış, orta sağlam kaya', ZC: 'Çok sıkı kum-çakıl / sert kil veya zayıf kaya', ZD: 'Orta sıkı-sıkı kum-çakıl / çok katı kil', ZE: 'Gevşek kum-çakıl / yumuşak-katı kil', ZF: 'Sahaya özel araştırma ve değerlendirme gerektirir' }
const isoCodes: SoilClassificationCode[] = ['CIL','CIM','CIH','SiL','SiM','SiH']
const tbdyCodes: SoilClassificationCode[] = ['ZA','ZB','ZC','ZD','ZE','ZF']
const n = (v: string) => v === '' ? 0 : Number(v)

export function ProjectInfoScreenV2() {
  const p = useProjectInfo(); const soil = p.soilParameters; const foundation = p.foundationParameters
  const set = <K extends keyof typeof p>(key: K, value: (typeof p)[K]) => updateProjectInfo({ ...p, [key]: value })
  const system = soil.classification?.system ?? 'TS EN ISO 14688-2'; const codes = system === 'TS EN ISO 14688-2' ? isoCodes : tbdyCodes
  const code = soil.classification?.code && codes.includes(soil.classification.code) ? soil.classification.code : codes[0]
  const vs30Group = classifyVs30(p.geophysical.vs30)
  const updateSeismic = (key: keyof typeof p.seismic, value: string) => set('seismic', { ...p.seismic, [key]: value === '' ? undefined : Number(value) })
  return <Frame screen="project-info">
    <Source>Proje bilgileri, jeofizik zemin sınıfı ve hazır deprem tehlike girdileri tek yerde tutulur. Grafik spektrum hesabı ayrı bir rapor çıktısıdır; işlem ağacında ayrıca Deprem ekranı yoktur.</Source>
    <div className="dashboard-grid"><div>
      <Card title="PROJE KİMLİĞİ"><div className="form-grid"><Field label="Proje Adı" type="text" value={p.title} onChange={(v) => set('title', v)} /><Field label="Proje No" type="text" value={p.projectNo} onChange={(v) => set('projectNo', v)} /><Field label="Tarih" type="date" value={p.date} onChange={(v) => set('date', v)} /><Field label="Mühendis" type="text" value={p.engineer} onChange={(v) => set('engineer', v)} /><Field label="Firma" type="text" value={p.firmName} onChange={(v) => set('firmName', v)} /><Field label="İşveren" type="text" value={p.clientName} onChange={(v) => set('clientName', v)} /><Field label="İl" type="text" value={p.province} onChange={(v) => set('province', v)} /><Field label="İlçe" type="text" value={p.district} onChange={(v) => set('district', v)} /><Field label="Adres" type="text" value={p.address} onChange={(v) => set('address', v)} /><Field label="Ada / Parsel" type="text" value={p.parcelInfo} onChange={(v) => set('parcelInfo', v)} /><Field label="Yapı Türü" type="text" value={p.buildingType} onChange={(v) => set('buildingType', v)} /><Field label="Kat" type="number" value={p.normalFloorCount || ''} onChange={(v) => set('normalFloorCount', n(v))} /><Field label="Bodrum Katı" type="number" value={p.basementCount || ''} onChange={(v) => set('basementCount', n(v))} /></div></Card>
      <Card title="JEOFİZİK · Vs30"><div className="geophysics-panel"><div className="vs30-input"><Field label="Vs30 (m/s)" value={p.geophysical.vs30 ?? ''} onChange={(v) => set('geophysical', { ...p.geophysical, vs30: v === '' ? undefined : Number(v), soilGroup: classifyVs30(v === '' ? undefined : Number(v)) })} /></div><div className="vs30-result"><span>Otomatik TBDY 2018 zemin grubu</span><strong>{vs30Group ?? '—'}</strong><small>{vs30Group ? descriptions[vs30Group] : 'Vs30 girildiğinde otomatik belirlenir.'}</small></div></div><div className="classification-note">ZF, yalnızca özel saha araştırması ve değerlendirmesiyle belirlenebildiğinden Vs30 tek başına ZF ataması yapmaz.</div></Card>
      <Card title="MÜHENDİSLİK ZEMİN SINIFLANDIRMASI"><div className="form-grid"><label>Sistem<select value={system} onChange={(e) => { const next = e.target.value as SoilClassificationSystem; const nextCodes = next === 'TS EN ISO 14688-2' ? isoCodes : tbdyCodes; set('soilParameters', { ...soil, classification: { system: next, code: nextCodes[0] } }) }}><option value="TS EN ISO 14688-2">TS EN ISO 14688-2</option><option value="TBDY 2018">TBDY 2018</option></select></label><label>Sınıflandırma Kodu<select value={code} onChange={(e) => set('soilParameters', { ...soil, classification: { ...soil.classification, code: e.target.value as SoilClassificationCode } })}>{codes.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label>Açıklama<input value={descriptions[code]} readOnly /></label></div><p className="classification-note">Bu sınıf saha SPT ve laboratuvar verilerinin mühendislik yorumundan gelir. Jeofizik Vs30 sınıfıyla birlikte raporda ayrı gösterilir.</p></Card>
      <Card title="HAZIR DEPREM TEHLİKE PARAMETRELERİ"><div className="form-grid"><Field label="Ss" value={p.seismic.ss ?? ''} onChange={(v) => updateSeismic('ss', v)} /><Field label="S1" value={p.seismic.s1 ?? ''} onChange={(v) => updateSeismic('s1', v)} /><Field label="Fs" value={p.seismic.fs ?? ''} onChange={(v) => updateSeismic('fs', v)} /><Field label="F1" value={p.seismic.f1 ?? ''} onChange={(v) => updateSeismic('f1', v)} /><Field label="Sıvılaşma deprem büyüklüğü Mw" value={p.seismic.magnitude ?? ''} onChange={(v) => updateSeismic('magnitude', v)} /></div><div className="classification-note">Ss, S1, Fs ve F1 hazır tehlike girdileridir. Mw yalnızca SPT tabanlı sıvılaşma değerlendirmesi için kullanılan ayrı bir proje girdisidir.</div></Card>
    </div><div>
      <Card title="ZEMİN TASARIM PARAMETRELERİ"><div className="form-grid"><Field label="γ · doğal birim hacim ağırlık (proje birimi)" value={soil.unitWeight || ''} onChange={(v) => set('soilParameters', { ...soil, unitWeight: n(v) })} /><Field label="γsat · doygun birim hacim ağırlık" value={soil.saturatedUnitWeight || ''} onChange={(v) => set('soilParameters', { ...soil, saturatedUnitWeight: n(v) })} /><Field label="c / cu · kohezyon veya drenajsız dayanım" value={soil.cohesion || ''} onChange={(v) => set('soilParameters', { ...soil, cohesion: n(v) })} /><Field label="φ′ · içsel sürtünme açısı (°)" value={soil.frictionAngle || ''} onChange={(v) => set('soilParameters', { ...soil, frictionAngle: n(v) })} /><Field label="β · zemin yüzey eğimi (°)" value={soil.surfaceSlope || ''} onChange={(v) => set('soilParameters', { ...soil, surfaceSlope: n(v) })} /><Field label="η · temel tabanı eğimi (°)" value={soil.foundationBaseSlope || ''} onChange={(v) => set('soilParameters', { ...soil, foundationBaseSlope: n(v) })} /><Field label="İnce dane oranı (%)" value={soil.finesContent || ''} onChange={(v) => set('soilParameters', { ...soil, finesContent: n(v) })} /></div></Card>
      <Card title="TEMEL TASARIM PARAMETRELERİ"><div className="form-grid"><Field label="B · temel genişliği (m)" value={foundation.footingWidth || ''} onChange={(v) => set('foundationParameters', { ...foundation, footingWidth: n(v) })} /><Field label="L · temel uzunluğu (m)" value={foundation.footingLength || ''} onChange={(v) => set('foundationParameters', { ...foundation, footingLength: n(v) })} /><Field label="Df · temel derinliği (m)" value={foundation.footingDepth || ''} onChange={(v) => set('foundationParameters', { ...foundation, footingDepth: n(v) })} /><Field label="Düşey tasarım yükü" value={foundation.verticalLoad || ''} onChange={(v) => set('foundationParameters', { ...foundation, verticalLoad: n(v) })} /><Field label="Yatay tasarım yükü" value={foundation.horizontalLoad || ''} onChange={(v) => set('foundationParameters', { ...foundation, horizontalLoad: n(v) })} /><Field label="Mx · moment" value={foundation.momentX || ''} onChange={(v) => set('foundationParameters', { ...foundation, momentX: n(v) })} /><Field label="My · moment" value={foundation.momentY || ''} onChange={(v) => set('foundationParameters', { ...foundation, momentY: n(v) })} /><Field label="FS" value={foundation.safetyFactor || ''} onChange={(v) => set('foundationParameters', { ...foundation, safetyFactor: n(v) })} /><Field label="γRv" value={foundation.resistanceFactorRv || ''} onChange={(v) => set('foundationParameters', { ...foundation, resistanceFactorRv: n(v) })} /></div></Card>
      <Card title="VERİ AKIŞI"><div className="workflow"><button type="button"><b>01</b><span>Proje kimliği + Vs30 + hazır deprem girdileri</span></button><button type="button"><b>02</b><span>Sondaj + SPT + laboratuvar ham verisi</span></button><button type="button"><b>03</b><span>Sondaj logu ve zemin profili yorumu</span></button><button type="button"><b>04</b><span>Korelasyonlar ve hesap parametrelerinin seçimi</span></button><button type="button"><b>05</b><span>Analizler ve ayrıntılı hesap izleri</span></button><button type="button"><b>06</b><span>Yatay A4 mühendislik raporu</span></button></div></Card>
    </div></div>
  </Frame>
}
