import { useState, type ReactNode } from 'react'
import './assets/main.css'
import './assets/workspace-polish.css'
import './assets/field-workspace.css'
import './assets/idealized-profile.css'
import { WorkspaceShell, type ScreenId } from './workspace/WorkspaceShell'
import { Dashboard, Foundation, JetGrout, Liquefaction } from './screens/EngineeringScreens'
import { IdealizedSettlementScreen } from './screens/IdealizedSettlementScreen'
import FieldInvestigation from './screens/FieldInvestigation'
import BoreholeLogScreen from './screens/BoreholeLogScreen'
import EngineeringReportScreen from './screens/EngineeringReportScreen'
import { ProjectInfoScreenV2 } from './screens/ProjectInfoScreenV2'
import { IdealizedSoilProfileScreen } from './screens/IdealizedSoilProfileScreen'
import { BearingCapacityScreen } from './screens/BearingCapacityScreen'
import { UnitConverterScreen } from './screens/UnitConverterScreen'
import { Foundation3DView } from './components/Engineering3DView'
import { defaultProjectInfo, normalizeProjectInfo } from '../../core/models/project'
import { updateProjectInfo, useProjectInfo } from '../../core/state/project-store'
import type { ProjectInfo as ProjectInfoModel } from '../../core/models/project'
import type { BoreholeRecord, LaboratoryRecord } from '../../core/models/field-data'
import type { IdealizedSoilProfile } from '../../core/models/idealized-soil-profile'
import { createEmptyBorehole } from '../../core/models/field-data-factory'

type ProjectDocument={projectInfo:ProjectInfoModel;boreholes:BoreholeRecord[];labs:LaboratoryRecord[];idealizedSoilProfile?:IdealizedSoilProfile}
function isProjectDocument(value:unknown):value is ProjectDocument{if(!value||typeof value!=='object')return false;const d=value as Partial<ProjectDocument>;return!!d.projectInfo&&Array.isArray(d.boreholes)&&Array.isArray(d.labs)}
function FieldCommandBar({boreholes,labs,onBoreholesChange,onLabsChange}:{boreholes:BoreholeRecord[];labs:LaboratoryRecord[];onBoreholesChange:(r:BoreholeRecord[])=>void;onLabsChange:(r:LaboratoryRecord[])=>void}){const[selectedId,setSelectedId]=useState(boreholes[0]?.id??'');const create=()=>{const b=createEmptyBorehole(boreholes.length+1);onBoreholesChange([...boreholes,b]);setSelectedId(b.id)};const remove=()=>{const t=boreholes.find(b=>b.id===selectedId);if(!t)return;if(!window.confirm(`${t.name} sondajını ve bu sondaja bağlı laboratuvar kayıtlarını silmek istiyor musunuz?`))return;onBoreholesChange(boreholes.filter(b=>b.id!==t.id));onLabsChange(labs.filter(l=>l.boreholeId!==t.id));setSelectedId(boreholes.find(b=>b.id!==t.id)?.id??'')};return <div className="field-command-bar"><div className="command-group"><span className="command-caption">SONDAJ YÖNETİMİ</span><button className="command-button primary" onClick={create}>＋ Yeni Sondaj</button><select value={selectedId} onChange={e=>setSelectedId(e.target.value)} disabled={!boreholes.length}><option value="">Sondaj seç</option>{boreholes.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><button className="command-button danger" onClick={remove} disabled={!selectedId}>Sil</button></div></div>}
export default function App(){const[screen,setScreen]=useState<ScreenId>('dashboard');const project=useProjectInfo();const[boreholes,setBoreholes]=useState<BoreholeRecord[]>([]);const[labs,setLabs]=useState<LaboratoryRecord[]>([]);const[idealizedSoilProfile,setIdealizedSoilProfile]=useState<IdealizedSoilProfile>();const[projectPath,setProjectPath]=useState<string>();const saveProject=async()=>{try{const path=await window.api.project.save({projectInfo:project,boreholes,labs,idealizedSoilProfile},projectPath);if(path)setProjectPath(path)}catch(e){console.error('ZeminLab proje kaydı başarısız:',e)}};const openProject=async()=>{try{const r=await window.api.project.open();if(!r||!isProjectDocument(r.data))return;updateProjectInfo(normalizeProjectInfo(r.data.projectInfo));setBoreholes(r.data.boreholes);setLabs(r.data.labs);setIdealizedSoilProfile(r.data.idealizedSoilProfile);setProjectPath(r.filePath);setScreen('dashboard')}catch(e){console.error('ZeminLab proje açma başarısız:',e)}};const newProject=()=>{updateProjectInfo({...defaultProjectInfo,id:crypto.randomUUID(),date:new Date().toISOString().slice(0,10)});setProjectPath(undefined);setBoreholes([]);setLabs([]);setIdealizedSoilProfile(undefined);setScreen('dashboard')};const field=<><FieldCommandBar boreholes={boreholes} labs={labs} onBoreholesChange={setBoreholes} onLabsChange={setLabs}/><FieldInvestigation boreholes={boreholes} labs={labs} onBoreholesChange={setBoreholes} onLabsChange={setLabs}/></>;const foundation=<><Foundation/><Foundation3DView boreholes={boreholes}/></>;const content:Record<ScreenId,ReactNode>={dashboard:<Dashboard onNavigate={setScreen}/>, 'project-info':<ProjectInfoScreenV2/>,field,borehole-log:<BoreholeLogScreen boreholes={boreholes} labs={labs} onBoreholesChange={setBoreholes}/>,profile:<IdealizedSoilProfileScreen boreholes={boreholes} labs={labs} profile={idealizedSoilProfile} onChange={setIdealizedSoilProfile}/>, 'bearing-capacity':<BearingCapacityScreen/>,settlement:<IdealizedSettlementScreen profile={idealizedSoilProfile} boreholes={boreholes}/>,liquefaction:<Liquefaction boreholes={boreholes} labs={labs}/>,foundation, 'jet-grout':<JetGrout/>,report:<EngineeringReportScreen boreholes={boreholes} labs={labs}/>, 'unit-converter':<UnitConverterScreen/>};return <WorkspaceShell screen={screen} onScreenChange={setScreen} onNewProject={newProject} onOpenProject={openProject} onSaveProject={saveProject}>{content[screen]}</WorkspaceShell>}
