import type { ReactNode } from 'react'
export type EngineeringRenderLayer={id:string;topDepth:number;bottomDepth:number;code?:string;description?:string;colorClass?:'fill'|'clay'|'silt'|'sand'|'gravel'|'rock';sptN?:number;gamma?:number;cohesion?:number;frictionAngle?:number;labId?:string}
export type EngineeringRenderMarker={depth:number;label:string;detail?:string;kind:'spt'|'lab'|'note'}
type Props={variant:'profile'|'borehole';totalDepth:number;groundwaterDepth?:number;foundationDepth?:number;layers:EngineeringRenderLayer[];markers?:EngineeringRenderMarker[];footer?:ReactNode}
const fmt=(v:number|undefined,d=2)=>v==null||!Number.isFinite(v)?'—':v.toFixed(d)
const pat=(code:string='')=>{const c=code.toLowerCase();if(c.includes('cl')||c.includes('ci')||c.includes('ch'))return'clay';if(c.includes('si')||c.includes('ml')||c.includes('mh'))return'silt';if(c.includes('gr')||c.includes('bo'))return'gravel';if(c.includes('sa'))return'sand';if(c.includes('kaya')||c.includes('rk'))return'rock';return'fill'}
export function EngineeringSectionRenderer({variant,totalDepth,groundwaterDepth,foundationDepth,layers,markers=[],footer}:Props){
 const d=Math.max(1,totalDepth),y=(v:number)=>60+Math.max(0,Math.min(d,v))/d*620,maxN=Math.max(30,...layers.map(x=>x.sptN||0)),soilX=variant==='profile'?130:105
 const auto=markers.length?markers:layers.flatMap(x=>x.sptN!=null?[{depth:(x.topDepth+x.bottomDepth)/2,label:'SPT',detail:'N='+fmt(x.sptN,0),kind:'spt' as const}]:[])
 return <div className="engineering-render-shell"><svg className="engineering-render-svg" viewBox="0 0 980 760" preserveAspectRatio="xMidYMin meet" role="img" aria-label="Mühendislik zemin kesiti">
  <defs>
   <pattern id="ers-fill" width="14" height="14" patternUnits="userSpaceOnUse"><rect width="14" height="14" fill="#d9dde0"/><path d="M0 14L14 0" stroke="#a6adb2"/></pattern>
   <pattern id="ers-clay" width="16" height="16" patternUnits="userSpaceOnUse"><rect width="16" height="16" fill="#d7b9a0"/><path d="M0 4h16M0 11h16" stroke="#99735c"/></pattern>
   <pattern id="ers-silt" width="14" height="14" patternUnits="userSpaceOnUse"><rect width="14" height="14" fill="#cdd4ca"/><circle cx="3" cy="3" r="1" fill="#7e887b"/><circle cx="10" cy="9" r="1" fill="#7e887b"/></pattern>
   <pattern id="ers-sand" width="14" height="14" patternUnits="userSpaceOnUse"><rect width="14" height="14" fill="#e4cf9b"/><circle cx="3" cy="4" r="1" fill="#a18245"/><circle cx="10" cy="10" r="1" fill="#a18245"/></pattern>
   <pattern id="ers-gravel" width="18" height="18" patternUnits="userSpaceOnUse"><rect width="18" height="18" fill="#c5cbcd"/><circle cx="4" cy="5" r="2" fill="#747d82"/><circle cx="13" cy="12" r="2" fill="#747d82"/></pattern>
   <pattern id="ers-rock" width="18" height="18" patternUnits="userSpaceOnUse"><rect width="18" height="18" fill="#b8bdc0"/><path d="M1 15L8 5L16 12" fill="none" stroke="#656d71"/></pattern>
  </defs>
  <rect width="980" height="760" fill="#f8fafb"/><rect width="980" height="44" fill="#e5e9ec" stroke="#9ca6ad"/>
  <text x="18" y="27" fontSize="10" fontWeight="700" fill="#3d4a53">DERİNLİK</text><text x="70" y="27" fontSize="10" fontWeight="700" fill="#3d4a53">ZEMİN KESİTİ</text><text x="590" y="27" fontSize="10" fontWeight="700" fill="#3d4a53">SPT</text><text x="760" y="27" fontSize="10" fontWeight="700" fill="#3d4a53">MÜHENDİSLİK PARAMETRELERİ</text>
  {Array.from({length:Math.ceil(d)+1},(_,i)=>{const yy=y(i);return <g key={i}><line x1="45" y1={yy} x2="960" y2={yy} stroke={i%5===0?'#c6cdd2':'#e4e7e9'} strokeWidth={i%5===0?1.2:.7}/><text x="34" y={yy+4} fontSize="9.5" textAnchor="end" fill="#5c6870">{i}</text></g>})}
  <rect x={soilX} y="60" width="430" height="620" fill="#fff" stroke="#78848b" strokeWidth="1.3"/>
  {layers.map(layer=>{const y0=y(layer.topDepth),y1=y(layer.bottomDepth),h=Math.max(1,y1-y0),k=layer.colorClass||pat(layer.code);return <g key={layer.id}><rect x={soilX} y={y0} width="430" height={h} fill={'url(#ers-'+k+')'} stroke="#707a81"/><text x={soilX+12} y={y0+16} fontSize="11" fontWeight="700" fill="#27333a">{layer.code||'—'} · {layer.description||'Zemin'}</text>{h>34&&<text x={soilX+12} y={y0+31} fontSize="9" fill="#4c5961">γ {fmt(layer.gamma)} · c {fmt(layer.cohesion)} · φ {fmt(layer.frictionAngle)}°</text>}</g>})}
  {layers.map(layer=>{if(layer.sptN==null)return null;const yy=(y(layer.topDepth)+y(layer.bottomDepth))/2,w=Math.max(0,Math.min(150,150*layer.sptN/maxN));return <g key={'spt-'+layer.id}><rect x="590" y={yy-8} width="150" height="16" fill="#eef1f3" stroke="#b4bcc2"/><rect x="590" y={yy-8} width={w} height="16" fill="#55738b"/><text x="746" y={yy+4} fontSize="9.5" fill="#43525c">N={fmt(layer.sptN,0)}</text></g>})}
  {layers.map(layer=>{const yy=(y(layer.topDepth)+y(layer.bottomDepth))/2;return <g key={'par-'+layer.id}><text x="760" y={yy-3} fontSize="8.8" fill="#4a565e">γ={fmt(layer.gamma)} c={fmt(layer.cohesion)} φ={fmt(layer.frictionAngle)}°</text><text x="760" y={yy+10} fontSize="8.3" fill="#68747c">{layer.labId?'LAB '+layer.labId:'LAB —'}</text></g>})}
  {auto.map((m,i)=>{const yy=y(m.depth),stroke=m.kind==='spt'?'#4b6980':m.kind==='lab'?'#6d826e':'#886c39';return <g key={i}><circle cx="75" cy={yy} r="5" fill="#fff" stroke={stroke} strokeWidth="1.5"/><text x="88" y={yy-2} fontSize="8.5" fontWeight="700" fill={stroke}>{m.label}</text>{m.detail&&<text x="88" y={yy+10} fontSize="8" fill="#59646b">{m.detail}</text>}</g>})}
  {groundwaterDepth!=null&&Number.isFinite(groundwaterDepth)&&groundwaterDepth>=0&&groundwaterDepth<=d&&<g><line x1="45" y1={y(groundwaterDepth)} x2="960" y2={y(groundwaterDepth)} stroke="#2f78a3" strokeWidth="2.4" strokeDasharray="9 5"/><text x="948" y={y(groundwaterDepth)-6} textAnchor="end" fontSize="9" fontWeight="700" fill="#2f678b">YASS {fmt(groundwaterDepth)} m</text></g>}
  {foundationDepth!=null&&Number.isFinite(foundationDepth)&&foundationDepth>0&&foundationDepth<=d&&<g><line x1={soilX} y1={y(foundationDepth)} x2={soilX+430} y2={y(foundationDepth)} stroke="#8b4f38" strokeWidth="2"/><text x={soilX+8} y={y(foundationDepth)-6} fontSize="9" fontWeight="700" fill="#8b4f38">TEMEL TABANI Df={fmt(foundationDepth)} m</text></g>}
  <line x1="720" y1="60" x2="720" y2="680" stroke="#98a1a7"/><text x="720" y="705" fontSize="8.5" fill="#657078">Vektörel teknik kesit · veri kaynaklı anotasyon · ölçeklenebilir</text>
 </svg>{footer&&<div className="engineering-render-footer">{footer}</div>}</div>
}
