export type SoilLayerInput={top:number;bottom:number;soil:string;gamma:number;gammaSat:number;cohesion:number;phi:number;fines:number}
export type SptInput={depth:number;nField:number;energyRatio?:number;borehole?:string;fines?:number}
export const deg=(v:number)=>v*Math.PI/180
export function stressAtDepth(depth:number,layers:SoilLayerInput[],gwt:number){let total=0,u=0;for(const l of layers){const a=Math.max(0,Math.min(depth,l.bottom)-Math.max(0,l.top));if(!a)continue;const mid=Math.max(0,l.top)+a/2;total+=a*(mid<=gwt?l.gamma:l.gammaSat);if(mid>gwt)u+=a*9.81}if(depth>layers.at(-1)?.bottom!){const z=layers.at(-1)?.bottom??0;total+=(depth-z)*(depth<=gwt?18:19.5);if(depth>gwt)u+=(depth-Math.max(z,gwt))*9.81}return{sigmaV:total,sigmaVPrime:Math.max(.1,total-u),u}}
export function sptCorrection(x:SptInput,sigmaV:number,sigmaVPrime:number){const CE=Math.max(.5,Math.min(1.5,(x.energyRatio??60)/60)),CB=1,CS=1,CR=x.depth<4?.75:x.depth<6?.85:x.depth<10?.95:1,CN=Math.min(2,Math.sqrt(100/Math.max(sigmaVPrime,1))),N60=x.nField*CE*CB*CS*CR,N160=Math.min(46,N60*CN);return{CE,CB,CS,CR,CN,N60,N160,sigmaV,sigmaVPrime}}
export type BearingMethod='Terzaghi'|'Meyerhof'|'Hansen'|'Vesic'
export function bearingCapacity(i:{B:number;L:number;Df:number;gamma:number;c:number;phi:number;FS:number;method:BearingMethod;waterReduction?:number}){const p=deg(i.phi),t=Math.tan(p),Nq=Math.exp(Math.PI*t)*Math.tan(Math.PI/4+p/2)**2,Nc=Math.abs(i.phi)<1e-9?5.14:(Nq-1)/t,Ng=i.method==='Meyerhof'?1.5*(Nq-1)*t:2*(Nq+1)*t,ratio=i.B/Math.max(i.L,i.B),sc=i.method==='Terzaghi'?1:1+.2*ratio,sq=i.method==='Terzaghi'?1:1+.1*ratio,sg=i.method==='Terzaghi'?1:Math.max(.6,1-.4*ratio),q=i.c*Nc*sc+i.gamma*i.Df*Nq*sq+.5*i.gamma*i.B*Ng*sg*(i.waterReduction??1),qn=q-i.gamma*i.Df;return{Nq,Nc,Ngamma:Ng,sc,sq,sg,ultimate:q,netUltimate:qn,allowableGross:q/i.FS,allowableNet:qn/i.FS,method:i.method}}
export function settlement(i:{B:number;q:number;Es:number;nu:number;layers?:{thickness:number;Cc?:number;e0?:number;sigma0?:number;dSigma?:number}[]}){const immediate=i.q*i.B*(1-i.nu*i.nu)/Math.max(i.Es,1),consolidation=(i.layers??[]).reduce((s,l)=>l.Cc&&l.e0!==undefined&&l.sigma0!==undefined&&l.dSigma!==undefined?s+l.thickness*l.Cc/(1+l.e0)*Math.log10((l.sigma0+l.dSigma)/Math.max(l.sigma0,1)):s,0);return{immediate,consolidation,total:immediate+consolidation}}
export function liquefaction(i:{Mw:number;amax:number;depth:number;N160:number;fines:number;sigmaV:number;sigmaVPrime:number}){const rd=Math.max(.9,1-.015*i.depth),CSR=.65*(i.sigmaV/i.sigmaVPrime)*(i.amax/9.81)*rd,fc=Math.max(0,Math.min(35,i.fines)),correction=fc<=5?0:Math.min(8,(fc-5)/3),Ncs=Math.min(46,i.N160+correction),CRR=.048*(Ncs/10)+.004*(Ncs/10)**2+.0002*(Ncs/10)**3,MSF=Math.max(.5,1+(7.5-i.Mw)/2.56),FS=CRR*MSF/Math.max(CSR,1e-6);return{rd,CSR,CRR,Ncs,MSF,FS}}
export function jetGrout(i:{columnDiameter:number;spacing:number;qultSoil:number;qultColumn:number;improvementFactor:number;FS:number;columnStrength:number}){const Ac=Math.PI*i.columnDiameter**2/4,ratio=Math.min(1,Ac/i.spacing**2),composite=(1-ratio)*i.qultSoil+ratio*i.qultColumn*i.improvementFactor;return{Ac,ratio,composite,allowable:composite/i.FS,columnLoad:Ac*i.columnStrength/i.FS}}
export function foundationChecks(i:{B:number;L:number;d:number;N:number;V:number;Mx:number;My:number;fy:number;cover:number}){const ex=i.My/Math.max(i.N,1e-9),ey=i.Mx/Math.max(i.N,1e-9),qAvg=i.N/(i.B*i.L),qMax=qAvg*(1+6*Math.abs(ex)/i.L+6*Math.abs(ey)/i.B),qMin=qAvg*(1-6*Math.abs(ex)/i.L-6*Math.abs(ey)/i.B),dEff=Math.max(.05,i.d-i.cover),AsX=i.N*i.L/(8*i.fy*dEff)*1e3,AsY=i.N*i.B/(8*i.fy*dEff)*1e3;return{ex,ey,qAvg,qMax,qMin,dEff,AsX,AsY}}
export const SOURCE_NOTES={investigation:'TBDY 2018 Ek 16A: zemin araştırma sondajları, arazi ve laboratuvar deneyleri.',liquefaction:'TBDY 2018 Ek 16B: SPT düzeltmeleri, sıvılaşma direnci ve depremde oluşan kayma gerilmesi.',bearing:'Terzaghi / Meyerhof / Hansen / Vesic yöntemleri; yönetmelik maddesi değil seçilen geoteknik yöntem olarak raporlanır.',settlement:'Elastik ve konsolidasyon oturması; parametrelerin deney/araştırma kaynağı raporda gösterilir.',foundation:'TBDY/TS500 tasarım girdileriyle kullanılmalıdır; eksik yapısal girdilerde sonuç nihai tasarım onayı değildir.',jetGrout:'Jet grout kompozit yaklaşımı proje deneyleri ve kolon dayanımı ile kalibre edilmelidir.'}
