import type { BoreholeRecord, LaboratoryRecord, SptRecord } from '../models/field-data'
import { calculateSpt, type SptEngineResult } from './spt/spt-engine'

export type PlasticityClass = 'CIL' | 'CIM' | 'CIH' | 'SiL' | 'SiM' | 'SiH'
export interface SoilClassificationResult { code: PlasticityClass; description: string; plasticityGroup: 'Düşük' | 'Orta' | 'Yüksek'; isClay: boolean; aLinePi: number }
export function classifyFineSoil(liquidLimit?: number, plasticityIndex?: number): SoilClassificationResult | null { if (!Number.isFinite(liquidLimit) || !Number.isFinite(plasticityIndex) || liquidLimit! <= 0) return null; const ll=liquidLimit!; const pi=plasticityIndex!; const aLinePi=.73*(ll-20); const isClay=pi>=aLinePi&&pi>=4; const group=ll<35?'Düşük':ll<=50?'Orta':'Yüksek'; const code=`${isClay?'CI':'Si'}${group==='Düşük'?'L':group==='Orta'?'M':'H'}` as PlasticityClass; return {code,description:`${group} Plastisiteli ${isClay?'Kil':'Silt'} (${code})`,plasticityGroup:group,isClay,aLinePi} }
export function laboratoryPlasticityIndex(record: LaboratoryRecord): number | undefined { if (Number.isFinite(record.plasticityIndex)) return record.plasticityIndex; if (Number.isFinite(record.liquidLimit)&&Number.isFinite(record.plasticLimit)) return record.liquidLimit!-record.plasticLimit!; return undefined }
export function fieldN(record: SptRecord): number | undefined { if (Number.isFinite(record.n2)&&Number.isFinite(record.n3)) return record.n2!+record.n3!; return undefined }
export type SptDerivedValues = Omit<SptEngineResult,'nField'> & { nField?: number; verticalStress?: number; effectiveStress?: number }
function layerAtDepth(borehole: BoreholeRecord, depth: number) { return borehole.lithology.find((layer)=>depth>=layer.from&&depth<layer.to) ?? borehole.lithology.find((layer)=>depth>=layer.from&&depth<=layer.to) }
function stressAtDepth(borehole: BoreholeRecord, depth: number) { const layer=layerAtDepth(borehole,depth); if(!layer?.unitWeight) return {verticalStress:undefined,effectiveStress:undefined}; const gamma=layer.unitWeight; const gammaSat=layer.saturatedUnitWeight??gamma; const gwt=borehole.groundwaterDepth; const z=Math.max(0,depth); const above=gwt===undefined?z:Math.min(z,Math.max(0,gwt)); const below=z-above; const verticalStress=above*gamma+below*gammaSat; const porePressure=gwt!==undefined&&z>gwt?(z-gwt)*9.80665:0; return {verticalStress,effectiveStress:Math.max(0,verticalStress-porePressure)} }
export function deriveSptValues(borehole:BoreholeRecord,record:SptRecord):SptDerivedValues { const nField=fieldN(record); if(nField===undefined) return {nField,ce:1,cb:1,cs:1,cr:1,cn:1,n60:0,n1_60:0,dilatancyApplied:false}; const stress=stressAtDepth(borehole,record.depth); const cfg=record.correction??{}; const result=calculateSpt({nField,energyRatio:cfg.energyRatio,effectiveStress:stress.effectiveStress,fineContent:cfg.fineContent??layerAtDepth(borehole,record.depth)?.finesContent,applyOverburden:cfg.applyOverburdenCorrection??true,applyDilatancy:cfg.applyDilatancyCorrection??false}); return {...result,verticalStress:stress.verticalStress,effectiveStress:stress.effectiveStress} }
export function classifyLaboratoryRecord(record: LaboratoryRecord): SoilClassificationResult | null { return classifyFineSoil(record.liquidLimit, laboratoryPlasticityIndex(record)) }
