export type UnitSystem='ton-m'|'kN-m'
export type FoundationType='tekil'|'surekli'|'radye'
export type SoilClassificationSystem='TS EN ISO 14688-2'|'TBDY 2018'
export type SoilClassificationCode='CIL'|'CIM'|'CIH'|'SiL'|'SiM'|'SiH'|'ZA'|'ZB'|'ZC'|'ZD'|'ZE'|'ZF'
export interface ProjectVisualDocuments{aerialPhoto?:string;layoutPlan?:string;architecturalSection?:string;foundationPlan?:string;foundationStress?:string}
export interface GeophysicalParameters{vs30?:number;soilGroup?:'ZA'|'ZB'|'ZC'|'ZD'|'ZE'|'ZF';source?:string;notes?:string}
export interface SeismicParameters{ss?:number;s1?:number;fs?:number;f1?:number;sds?:number;sd1?:number;ta?:number;tb?:number;tl?:number;magnitude?:number}
export interface SoilClassification{system:SoilClassificationSystem;code?:SoilClassificationCode}
export interface SoilParameters{unitWeight:number;saturatedUnitWeight:number;cohesion:number;frictionAngle:number;groundwaterDepth?:number;surfaceSlope:number;foundationBaseSlope:number;finesContent:number;classification:SoilClassification}
export interface FoundationParameters{foundationType:FoundationType;footingWidth:number;footingLength:number;footingDepth:number;safetyFactor:number;verticalLoad:number;horizontalLoad:number;momentX:number;momentY:number;resistanceFactorRv:number;vtX:number;vtY:number;structuralWeight:number}
export interface ProjectInfo{id:string;title:string;projectNo:string;date:string;location:string;province:string;district:string;address:string;parcelInfo:string;pafta:string;ada:string;parsel:string;zoningStatus:string;engineer:string;clientName:string;firmName:string;buildingType:string;basementCount:number;normalFloorCount:number;unitSystem:UnitSystem;geophysical:GeophysicalParameters;seismic:SeismicParameters;soilParameters:SoilParameters;foundationParameters:FoundationParameters;visualDocuments:ProjectVisualDocuments}
export const defaultProjectInfo:ProjectInfo={id:'',title:'',projectNo:'',date:'',location:'',province:'',district:'',address:'',parcelInfo:'',pafta:'',ada:'',parsel:'',zoningStatus:'',engineer:'',clientName:'',firmName:'',buildingType:'',basementCount:0,normalFloorCount:0,unitSystem:'ton-m',geophysical:{},seismic:{},soilParameters:{unitWeight:0,saturatedUnitWeight:0,cohesion:0,frictionAngle:0,groundwaterDepth:undefined,surfaceSlope:0,foundationBaseSlope:0,finesContent:0,classification:{system:'TS EN ISO 14688-2'}},foundationParameters:{foundationType:'tekil',footingWidth:0,footingLength:0,footingDepth:0,safetyFactor:0,verticalLoad:0,horizontalLoad:0,momentX:0,momentY:0,resistanceFactorRv:1.4,vtX:0,vtY:0,structuralWeight:0},visualDocuments:{}}
export function classifyVs30(vs30?:number):GeophysicalParameters['soilGroup']{if(vs30===undefined||!Number.isFinite(vs30)||vs30<=0)return undefined;if(vs30>=1500)return'ZA';if(vs30>=760)return'ZB';if(vs30>=360)return'ZC';if(vs30>=180)return'ZD';return'ZE'}
const UNIT_SYSTEMS:readonly UnitSystem[]=['ton-m','kN-m']
export function normalizeProjectInfo(value:Partial<ProjectInfo>):ProjectInfo{const soil=value.soilParameters??defaultProjectInfo.soilParameters;const foundation=value.foundationParameters??defaultProjectInfo.foundationParameters;const unitSystem=UNIT_SYSTEMS.includes(value.unitSystem as UnitSystem)?value.unitSystem as UnitSystem:defaultProjectInfo.unitSystem;const foundationType=foundation.foundationType==='surekli'||foundation.foundationType==='radye'||foundation.foundationType==='tekil'?foundation.foundationType:'tekil';return {...defaultProjectInfo,...value,unitSystem,geophysical:value.geophysical??{},seismic:value.seismic??{},soilParameters:{...defaultProjectInfo.soilParameters,...soil,classification:{...defaultProjectInfo.soilParameters.classification,...(soil.classification??{})}},foundationParameters:{...defaultProjectInfo.foundationParameters,...foundation,foundationType},visualDocuments:value.visualDocuments??{}}}
